### ISSUE TITLE
[BUG_SP] The overloader will avoid cultivation even though I have disabled this option.

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/Courseplay_FS22#2993] opened 2023-12-03 16:59 UTC
I deactivate the option: "Avoid crops" because I lose too much FPS when the tractor searches for its route.
Despite this, the tractor will still avoid the harvest to go to the unloading point. This option no longer works since the last Courseplay update.
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/0d8ef6a2-04e3-4ec6-949d-3da1dde82002)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/6cbded85-a6f8-46f5-93eb-cf4a4f73b857)

**Comment by Tensuko** [comment] 2023-12-09 13:00
Avoid fruit off:
![fsScreen_2023_12_09_13_58_43](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/90233abe-5843-4ab0-9db6-111e1744b78f)

Avoid fruit on:
![fsScreen_2023_12_09_13_58_52](https://github.com/Courseplay/Courseplay_FS22/assets/27344744/56c3cd03-99d1-4893-b86d-e882caabd1c3)

Can't reproduce.
Might be fixed for next Version only, but I don't know why it should not work with 7.4.0.0 as we did not touch it.
Anyway, can't reproduce, but may wait for next Version.

**Comment by Crinouche** [comment] 2023-12-09 17:01
To go to the combine, the tractor will not avoid the crops.
It's on the way back that it avoids crops, even though I deactivated the function

![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/eb674144-c073-47de-937a-92a455b8567b)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/b97b8e17-ca8c-4a62-867c-3c2865603b43)
![image](https://github.com/Courseplay/Courseplay_FS22/assets/36656729/e4c8d691-008f-4d1b-acaf-f66abb2a08e8)

**Comment by Tensuko** [comment] 2023-12-09 19:41
Ok will check this tmr.

**Comment by Tensuko** [comment] 2023-12-10 11:04
fixed with next release

**Closed by Tensuko** 2023-12-10 11:04 UTC
Labels: bug
