### ISSUE TITLE
[BUG_SP] Problem with Bourgault Drill if user does not sit in tractor

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#1305] opened 2022-03-29 21:07 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Using the big Bourgault drill (Modhub) with the Vario 1167 MT (Vanilla). Course with 2 Headlands, up&down in center with 1 skip row. 

**Actual behavior**
As long as the user sits in the tractor, everything is fine, but after leaving for 20-30 seconds, the tracter and drill start making strange turns and more or less stop advancing on the course. As soon as I switch back into the tractor, it starts working properly again (without any other interaction). The behavior can be seen in the attached video. 

**Expected behavior**
The same behavior during "user absence" in the cab as with "user presence" in the cab

**Screenshots**
https://youtu.be/lknvlWreAsY

**Courseplay version**
7.0.1.7

**Log**
https://gist.github.com/DemsMani/604f5b786c4dc395840cbb123b671119

**Map**
County Line

**Vehicles/ implements involved**
Bourgault drill from Modhub (Bourgault 3320-76 Paralink Hoe Drill + 7950 Air Cart), Fendt Vario 1167MT (Vanilla)

**Relevant script mods**
Courseplay and Autodrive

**Comment by Tensuko** [comment] 2022-03-30 17:41
I have my doubt the reason is "not sitting in the tractor" I am sure there is another reason.

**Comment by DemsMani** [comment] 2022-03-30 19:50
> I have my doubt the reason is "not sitting in the tractor" I am sure there is another reason.

I find that strange as well, yes. But it somehow seems like it works if I am at least in the area (maybe if it needs to be rendered) and stops working properly if I am at other places of the map. I will try again if I can isolate the problem a bit better

**Comment by DemsMani** [comment] 2022-03-30 21:53
I tried it again while standing close, this also seemed to work. @Tensuko: Yes the "straight" lines on my field looked exactly like these on your picture.

**Comment by Tensuko** [comment] 2022-03-31 06:34
What if you chose another tractor, does the same happen ?

**Comment by DemsMani** [comment] 2022-03-31 06:39
Will try tonight

**Comment by rohne83** [comment] 2022-03-31 08:58
That is a known bug, caused by this vehicle. Don't know what exactly Giants has done wrong here, but it's not a CP problem, it's known to appear with standard helper as well.

**Comment by Tensuko** [comment] 2022-03-31 10:50
> That is a known bug, caused by this vehicle. Don't know what exactly Giants has done wrong here, but it's not a CP problem. It's known to appear with standard helper as well, that everytime that you don't sit in the tractor the trailer starts to drive its own lane.

Thank you for that Information.
Thats just wow.....

Ok I will close this then.

**Closed by Tensuko** 2022-03-31 10:50 UTC
Labels: bug
