### ISSUE TITLE
Offset Tools

### ISSUE THREAD

**Issue by knoxville73** [Courseplay/Courseplay_FS22#162] opened 2021-12-27 09:16 UTC
I use this configuration to cut the grass (see first picture).  The settings for this is to use an offset of 2.3 m to left.  The problem, to do the maneuver at the end of the line, the tractor is much too large (see other pictures)

![fsScreen_2021_12_27_09_50_17](https://user-images.githubusercontent.com/23388102/147456214-786901dd-6582-4fad-9723-0474de0b5020.png)
![fsScreen_2021_12_27_09_50_45](https://user-images.githubusercontent.com/23388102/147456237-ec6da372-a17f-4685-a9bf-ed4bd13f2a2b.png)
![fsScreen_2021_12_27_09_50_48](https://user-images.githubusercontent.com/23388102/147456248-16b62604-9cba-4ce2-bcce-c9edbb56e95c.png)

**Comment by pvaiko** [comment] 2021-12-27 11:59
Duplicate of #141

**Comment by Tensuko** [comment] 2021-12-28 13:35
Pls try 7.0.0.8
Reopen if Error persists.

**Closed by Tensuko** 2021-12-28 13:35 UTC
Labels: bug
