### ISSUE TITLE
[BUG_SP] Collecting/Wrapping bales Ai Stuck in a left reverse circle.

### ISSUE THREAD

**Issue by k4talin** [Courseplay/Courseplay_FS22#2384] opened 2023-03-18 04:04 UTC
Ai does get stuck in reverse and never recover while wrapping bales using the in game KUHN SW4014.
The Ai ignore the noReverse settings in the VehicleConfigurations.xml:
    
    <Vehicle name="sw4014.xml"
             toolOffsetX="-2.5"
             noReverse="true"
I saw him reversing many many times. If reverse happens more than like 2 seconds he will be stuck in that circle forever.
It happens on any field , using any tractor I tried. I never encounter a wrapping job done from start to the end without me going to stop and restart the AI which i always find in that reversing to the left circle.
I will upload a video to show what it happens at least 3 times per field evry time.

https://user-images.githubusercontent.com/67529028/226083923-10fb087f-0695-434b-9963-04c6705aaf6d.mp4

Curently Map name is Elmcreek base game map. No modded vehicle or tools. No custom field.

**Comment by Tensuko** [comment] 2023-03-18 07:21
Hmm that is not rly ignore I think, the problem is that the config is not checked in that mode. The Tractor have to reverse to get space infront of him to drive to the next target. Will check what we can do about that.

**Comment by k4talin** [comment] 2023-03-19 00:45
Ty Sir. It happens every field. 2-3 times per field. Any tractors. I did notice it happens less with very high power tractors like over 400 hp. It seems they reverse and push the kuhn like ignoring it just because the kuhn does not affect their reverse trajectory even if it is pushed badly in one side. so they don't get stuck very often. I was watching many times and it seems if the tractor do not reverse they will finish job spot on. Simple fix will be disable reverse for this task.

**Closed** 2023-03-20 17:38 UTC
Labels: bug
