### ISSUE TITLE
 custom feilds on other maps

### ISSUE THREAD

**Issue by Abram19** [Courseplay/Courseplay_FS22#3237] opened 2024-05-08 17:55 UTC
**READ FIRST**
[](https://github.com/Courseplay/Courseplay_FS22/wiki)

**Steps to reproduce**
make two savegames with the same map and make cutom feild

**Actual behavior**
the same custom feilds on both savegames

**Expected behavior**
both savegames to not have the same custom feilds

**Screenshots**
![Screenshot 2024-05-08 115119](https://github.com/Courseplay/Courseplay_FS22/assets/169295162/8f7c0946-0121-429c-908d-35f775437685)
![Screenshot 2024-05-08 115014](https://github.com/Courseplay/Courseplay_FS22/assets/169295162/c0c6ba94-d49d-4651-8104-210b9ce9d110)

**Courseplay version**
Version used: 7.4.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.gnadenthal

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by Tensuko** [comment] 2024-05-08 19:23
Not a bug, working as intended.
Custom fields are saved per map, won't fix.

**Closed by Tensuko** 2024-05-08 19:23 UTC
Labels: bug

**Comment by Abram19** [comment] 2024-05-08 19:54
so I cant have two of the same maps with differnt custom feilds?

**Comment by Tensuko** [comment] 2024-05-08 20:23
No.

**Comment by Abram19** [comment] 2024-05-08 20:26
so that cant be changed?

**Comment by Tensuko** [comment] 2024-05-09 06:13
We will not do that.

**Comment by Tensuko** [comment] 2024-05-09 06:14
In mod settings is a cp folder, there are custom fields saved, you can copie them arround when you change savegame.

**Comment by Abram19** [comment] 2024-05-09 19:44
Ok,thanks
