### ISSUE TITLE
[BUG_SP] Cannot clear course or hide 'show' course when auger wagon connected

### ISSUE THREAD

**Issue by Krecik7** [Courseplay/Courseplay_FS22#1993] opened 2022-10-09 14:46 UTC
**Steps to reproduce**
Attach tractor to i.e. spreader, create/load course, click on 'show course', you see lines. All ok. But, later, disconnect spreader and connect auger wagon, now you still see course, but you cannot hide it or clear it. Same situation when i have Siloking trailer connected or Bergman HTW65 or Krone GX 520 standard trailer. 

**Expected behavior**
Active clear course button, or automatic HIDE shown course

**Screenshots**
WIth auger wagon and loaded course - no 'hide course' / 'clear course' button active, and i see last used course
![image](https://user-images.githubusercontent.com/114803494/194763227-c7bc183b-de49-4fa7-995c-d7c65964103d.png)

after auger wagon is disconnected i can hide loaded track
![image](https://user-images.githubusercontent.com/114803494/194763228-d46b4302-376e-4c4f-a0ec-5a033b8686b6.png)

**Courseplay version**
7.1.1.3

**Map**
PGR Śliwno

**Comment by Tensuko** [comment] 2022-10-09 15:10
It is not intended to have a course loaded when connecting an auger wagon or trailer or anything.
When you disconnect the trailer or auger wagon and then can do it, its fine.

Working as intended, won't fix.

**Closed by Tensuko** 2022-10-09 15:10 UTC
Labels: bug

**Comment by Krecik7** [comment] 2022-10-09 15:15
But it does'nt make sense to have need to clear course BEFORE i connect any trailer (look that with some trailers it works different) ... Meaby it is possible just to set 'dont show' loaded course when it is useless.

**Comment by Tensuko** [comment] 2022-10-09 15:52
And I don't understand when you have so many opportunities to clear the course or hide it (have the tool conencted, have to tool disconnected, untill you connect a trailer) why you can#t do that before..... Won't fix.....

**Comment by Krecik7** [comment] 2022-10-09 16:26
1. I play on keyboard, and until now you didn'nt do keyboard shortcut to clear course, or change its visibility
2. I play mostly with HUD disabled, so now I will have to check everytime i'm connecting trailer, if i have loaded course (which is no problem) and if i have show course (which is a problem)
3. this "feature" is not working continously - i.e with trailer Rundolph TDK 301RP that has DK280 connected (two trailers) you can clear course and change it's visibility - this is why in my opinion its not a feature it's a bug under development ;) (ok, meaby it's another bug - when you have two trailers then 'auger wagon mode' is not working). 

Only problem is with visibility of course when its useless when you drive to some field with trailers to do some other work.

**Comment by Tensuko** [comment] 2022-10-09 16:35
> 1. play on keyboard, and until now you didn'nt do keyboard shortcut to clear course, or change its visibility, i have to use mouse, i don't use mouse if i really don't need to use it...

Wrong. Read changelog!



> 3\. this "feature" is not working continously - i.e with trailer Rundolph TDK 301RP that has DK280 connected (two trailers) you can clear course and change it's visibility - this is why in my opinion its not a feature it's a bug under development ;) (ok, meaby it's another bug - when you have two trailers then 'auger wagon mode' is not working).

This feature is working 100% correctly!
Two Trailers are not supported and won't ever be due to reverse driving wich is impossible with two trailers.
Becouse of the Mod blocked, it is like you have nothing connected at all! What is a bug and what not, we know it.



> Only problem is with visibility of course when its useless when you drive to some field with trailers to do some other work.

There is no problem when you JUST have to unconnect the trailer and toggle it then reconnect OR what most ppl do when work is finished, just do it BEFORE you do anything else.

Thats intended.

**Comment by Krecik7** [comment] 2022-10-09 16:41
> Wrong. Read changelog!

Which relase ? I did'nt find any info (and configuration option) to configure keybind to clear course or change visibility. 




> > 1. play on keyboard, and until now you didn'nt do keyboard shortcut to clear course, or change its visibility, i have to use mouse, i don't use mouse if i really don't need to use it...
> 
> Wrong. Read changelog!

There are keybinds to clear course or to change visibility ? I did'nt find any information about this in changelog.

**Comment by Tensuko** [comment] 2022-10-09 16:43
7.1.1.0
Added some key inputs

**Comment by Krecik7** [comment] 2022-10-09 17:01
> 7.1.1.0 Added some key inputs

Yess, i'm using them from begining :-) I love 'change starting point' keybind and 'open course manager' shortcut, but there is no 'clear course' and 'change course visibility' :-) 

Please, add this two, please please :)
