### ISSUE TITLE
[BUG_SP] Seeder not lowered soon enough :(

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1023] opened 2022-02-17 15:50 UTC
**Steps to reproduce**
Create a course with a seeder

**Actual behavior**
when beginning a row, seeder is not lowered soon enough, even if the driver set the implement to lower early
happen since 7.0.1.0, it was ok with previous versions

**Expected behavior**
seeder to be lowered soon enough to seed all the field

**Screenshots**
![Sans titre](https://user-images.githubusercontent.com/58886243/154517725-6d959e44-65f7-400e-a4fb-e6f3cb11e2e3.png)
https://drive.google.com/file/d/12AMSlNScthqexhohPsGHUY4-LVOXK1QU/view?usp=sharing

**Courseplay version**
Version used: 7.0.0.1
it was ok with the same équipement on previous versions

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8090005/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Class Axion 960 + Kvenerland DGII 12000 (mod from modhub, but used without any problem with previous CP version)

**Relevant script mods**
Autodrive

**Comment by Tensuko** [comment] 2022-02-17 15:51
Might be fixed with next version
Could be same problem as #1000

**Comment by pvaiko** [comment] 2022-02-17 19:35
Yes, looks like it is the same.

**Comment by Tensuko** [comment] 2022-02-18 12:31
Should be fixed in 7.0.1.1

**Closed by Tensuko** 2022-02-18 12:31 UTC
Labels: bug

**Comment by pvaiko** [comment] 2022-02-19 11:34
@Chico0008 can you show me what the problem is? I can't reproduce it. Log, vehicle settings, maybe a video.

**Comment by Chico0008** [comment] 2022-02-19 11:45
![Sans titre](https://user-images.githubusercontent.com/58886243/154799340-465ec06f-029d-4b01-a626-85f8888c98aa.png)

as you can see, there are still some empty left, not seeded :/
not as big as en 7.0.1.0, but still some missing point (work was done with 7.0.1.2)
i won't be able to post a log for now, i'm leaving on holiday for a week

**Comment by Chico0008** [comment] 2022-02-27 09:00
Hi, back from holiday

have the same with other implement
i'm with dablo maxiroll 630 (2 driver with same tractor/implement)

maybe set the work start line earlier ? or making the row more closer to the headland pass ?
(done with CP 7.0.12)
![1](https://user-images.githubusercontent.com/58886243/155875651-926ce9a9-dfc5-424e-8c32-d4843cd9a53a.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8148374/log.txt)

i'll try making a new log with seeded in the week
