### ISSUE TITLE
[BUG_SP] Bunker Silo Mode no more usage of L10n in HUD ?

### ISSUE THREAD

**Issue by Lactic68** [Courseplay/Courseplay_FS22#2143] opened 2022-11-27 13:17 UTC
**Steps to reproduce**
CP 7.1.2.3 installed, jump to a vehicle equiped with leveler or roller for bunker usage.
The HUD is in english regardless the selected language (in this case French)

**Actual behavior**
HUD is in English only

**Expected behavior**
HUD might use the L10n files

**Screenshots**
![2022-11-27_13-47-12](https://user-images.githubusercontent.com/70093234/204136224-d819fb1d-ecfd-4b3e-8a67-f866e1549f80.png)

**Courseplay version**
Version used: 7.1.2.3

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10098403/log.txt)

**Map**
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement? Leveler and compacter
Mod yes/no ? No

**Relevant script mods**
Vanilla

**Comment by Tensuko** [comment] 2022-11-27 16:13
Could not reproduce, may be fixed in 7.1.2.4
![grafik](https://user-images.githubusercontent.com/27344744/204145330-efb70f23-e220-43bc-a27e-4c30258ce29f.png)

**Comment by Tensuko** [comment] 2022-11-27 18:55
Try it with 7.1.2.4
For me it worked.

**Closed by Tensuko** 2022-11-27 18:55 UTC
Labels: bug
