### ISSUE TITLE
[BUG_SP] Strange debug text popping up

### ISSUE THREAD

**Issue by reanopp** [Courseplay/Courseplay_FS22#410] opened 2022-01-07 17:30 UTC
**Steps to reproduce**
Tractor with a planter is busy planting crops on a field with CP. I'm in a different tractor driving around that's not currently under CP control. Orange debug text keeps on popping up in the non-CP tractor with huge fps impact. This happens roughly every 10 seconds or so.

**Screenshots**
The text doesn't appear on screenshots for some reason. But it looked like this, near the bottom of the screen, in orange:
xte=-0.0 oe=-0.0 ce=0.0 current=-0.1 reference=-0.1 correction=0.0

**Courseplay version**
7.0.0.16

**Log**
[log2.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830341/log2.txt)

**Map**
No Man's Land

**Comment by Tensuko** [comment] 2022-01-07 17:40
Where is the complete logfile ?

**Comment by reanopp** [comment] 2022-01-07 17:42
> Where is the complete logfile ?
@Tensuko 
Sorry, wrong file. Here's this session's file attached. (I have a python script number the log files for each play session and sometimes I get confused :D
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830409/log.txt)

**Comment by nlcoredump** [comment] 2022-01-07 17:45
I have seen same thing, seems to be happening when a (not necessarily selected) vehicle is reversing in a job.

**Comment by reanopp** [comment] 2022-01-07 17:46
> I have seen same thing, seems to be happening when a (not necessarily selected) vehicle is reversing in a job.

Looks like you're right. Didn't happen before 7.0.0.16 though, maybe a debug print leftover?

**Comment by RealNeo80** [comment] 2022-01-07 18:02
yep can confirm i have this also
![image](https://user-images.githubusercontent.com/8066324/148586925-170257e6-cafe-4504-8488-5976757c5a9f.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7830516/log.txt)

**Comment by pvaiko** [comment] 2022-01-07 19:06
Duplicate of #404 #397, already fixed in 61bbe0b8 as I'm sure @Tensuko knows :)

**Closed by pvaiko** 2022-01-07 19:06 UTC
Labels: bug

**Comment by Tensuko** [comment] 2022-01-07 19:43
@pvaiko on current main state of our branch is stills pops up (just the yellow text, like seen on that screenshot).

**Comment by Tensuko** [comment] 2022-01-07 19:53
Jep is fixed, sry I think I had debug on on some vehicle when tested this...
