### ISSUE TITLE
[BUG_MP] Courseplay goes swimming more often

### ISSUE THREAD

**Issue by Selyria** [Courseplay/Courseplay_FS22#1454] opened 2022-04-22 17:58 UTC
Steps to reproduce

Curseplay course loaded and run 

sometimes curseplay goes swimming

Actual behavior

Curseplay goes swimming

Expected behavior

Curseplay should not drift kilometers off course

Screenshots

<img width="1281" alt="Baden" src="https://user-images.githubusercontent.com/179698/164769153-913f76eb-c915-437e-b2f9-6261ccf24954.png">

Unfortunately it always happens when I am not looking

Courseplay version

Version used: 7.0.1.13

Client Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8542955/log.txt)

Server Log

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8542703/log.txt)

Player on the server
4

Dedicated server or local hosted server
Dedicated server Yes

Map

Nordfriesische Marsch 4fach] 1.5

Vehicles/ implements involved

Kein Mod Fahrzeug

Relevant script mods
Autodrive 2.0.0.5

**Comment by Tensuko** [comment] 2022-04-24 18:23
Need logfile with debugchannel active.

If you send me the course file, I may can try to reproduce this when I have time.

But total drive off from course I haven't noticed.

**Comment by Selyria** [comment] 2022-04-24 19:53
Okay I will try to reproduce the things again

**Comment by Selyria** [comment] 2022-04-25 19:43
Which debug channels do I need to have active for posting bugs???

**Comment by Tensuko** [comment] 2022-04-26 07:44
Just turn on debug for the vehicle, everything else comes automatically if you have not turned it off on your side.

**Comment by Selyria** [comment] 2022-04-26 08:10
<img width="1283" alt="Unbenannt" src="https://user-images.githubusercontent.com/179698/165253057-6cd445c1-fd89-41ec-85df-d9212490a381.png">

These are the Chanels I have active.
I hope I had not switched off

**Comment by matze0301** [comment] 2022-04-27 08:16
Cross Reference:
https://github.com/Courseplay/Courseplay_FS22/issues/1478

**Comment by Selyria** [comment] 2022-04-27 21:01
okay good to know I have not yet been able to recreate the problem but #1478 I agree so it was certainly the same for me.

**Comment by pvaiko** [comment] 2022-04-28 11:09
Duplicate of #1478

**Closed by pvaiko** 2022-04-28 11:09 UTC
Labels: bug, waiting for user, multiplayer
