### ISSUE TITLE
[BUG_SP]Wrong direction at the startpoint after generating a course via helper-menue

### ISSUE THREAD

**Issue by MisterGeniusj007** [Courseplay/Courseplay_FS22#302] opened 2022-01-02 00:53 UTC
**Steps to reproduce**
Steps to reproduce the behavior.
-> Set the start point in a corner of a field, take the direction and than the startpoint is flipping by 90°!

**Actual behavior**
A clear and concise description of what happen.
- The direction of the startpoint is flipping sometimes for 90°

**Expected behavior**
I thought that with the definition of the direction these will included in the course!

**Screenshots**

**Courseplay version**
Version used: 7.0.0.10

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.
- Elmcreek

**Vehicles/ implements involved**
Mod yes/no ?
Sometimes, but in these documented example there is used a vanilla-machine

**Relevant script mods**
Mods like Autodrive or VCA and so on.
-Autodrive
- Enhanced Vehicle
![Screenshot 2022-01-02 014148_lr](https://user-images.githubusercontent.com/53146565/147863358-e67e2672-1503-4c48-aa8a-0cb3df72fa87.png)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798410/log.txt)
![Screenshot 2022-01-02 014002](https://user-images.githubusercontent.com/53146565/147863360-c82c053e-8406-46d9-899d-12d7637afbb0.png)
![Screenshot 2022-01-02 013859](https://user-images.githubusercontent.com/53146565/147863361-5cb74be0-9233-4618-b95e-35be104acabc.png)

**Comment by MisterGeniusj007** [comment] 2022-01-02 00:54
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7798411/log.txt)

**Comment by pvaiko** [comment] 2022-01-02 01:41
If you mean the direction of the sign (white arrow on blue sign), it has been fixed in 502789d9. 

If you mean something else, then reopen and give us a better explanation, German is fine too.

**Closed by pvaiko** 2022-01-02 01:41 UTC
Labels: bug

**Comment by MisterGeniusj007** [comment] 2022-01-02 11:48
Hy Pvaiko, in my version these problem is existing one more time!
And the machine is accepting these shown direction! It is not an absolut killing error, more looking funny!
If I know these trouble a can create a solving-work-arround by myself and all is fine!

Have I to change some code-lines?

**Comment by pvaiko** [comment] 2022-01-02 13:17
Seems to be a duplicate of #301
