### ISSUE TITLE
Suggestion: check if harvester is unfolded before starting and if it is, don't try to fold and unfold.

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#83] opened 2021-12-25 13:34 UTC
If I've got 2 fields with the same crop, I might not empty the harvester in between. If it has even a tiny bit of grain in it won't fold so it's impossible to start working on the next field until I've emptied it. I don't see an option for this (only "fold at end of work"). Of course the easy answer is to stop being lazy and make sure I empty the combine between courses but if I start a course with any unfolded implement, it'd still be nice to not have to wait for Courseplay to fold and unfold it.

**Comment by pvaiko** [comment] 2021-12-25 13:37
Not sure what exactly the problem here is. We need a step-by-step description of how to reproduce the problem, what is the expected behavior and what is the actual.

(Note to self: add issue template)

**Comment by ph1go** [comment] 2021-12-25 13:49
You can only "fold" a combine if it's empty - if it has any grain in it at all, the game will refuse to fold it (with error "folding is not allowed while the tool is filled"). Courseplay insists on either starting a course with a folded implement - even if it's already unfolded, Courseplay will fold it and then unfold it before starting.

The expected behaviour (in my mind) would be for Courseplay to realise that the tool is unfolded, skip the folding/unfolding step and start the fieldwork.

To reproduce the problem, try to start combining a field with a Courseplay course with a non-empty combine.

**Comment by pvaiko** [comment] 2021-12-25 13:53
> To reproduce the problem, try to start combining a field with a Courseplay course with a non-empty combine.

Doing that all the time. No issues, as combine is unfolded, as you can't fold it if it is not empty. 

I'm not aware of CP trying to fold anything when starting fieldwork.

**Comment by ph1go** [comment] 2021-12-25 14:05
> I'm not aware of CP trying to fold anything when starting fieldwork.

That's weird, it does it for every foldable implement I've tried with CP so far... the combine, cultivators/seeders/planters, the big Bruin sprayer... When I absent-mindedly forget about the issue I'm describing and set up a course with an unfolded implement and click "start job", the first thing CP does is fold/unfold it before starting the fieldwork. I thought there might be some crosstalk with AIVE but I don't ever use that mod for anything other than harvesting so it's disabled on all other vehicles.

**Comment by pvaiko** [comment] 2021-12-25 14:47
Ok, turn on the mode 4 and 6 and implements debug channel and post a log. 

And make sure you are using the latest 7.0.0.4

**Comment by Tensuko** [comment] 2021-12-25 15:40
The problem is if you start an unfolded combine with 'start Job menu' it will always try to drive to the set location.
Giants doesn't allow the tools to be driven unfolded so it tries to fold them, wich is not possible with a filled combine.
It should be no problem, if you drive it by yourself and press H.
If you want to to driv to the field by yourself, then make sure the combine is empty.
If the combine is empty and it still does not work, do like @pvaiko turn on the debugchannels and post the logfile.

**Comment by ph1go** [comment] 2021-12-25 15:55
> The problem is if you start an unfolded combine with 'start Job menu' it will always try to drive to the set location. Giants doesn't allow the tools to be driven unfolded so it tries to fold them, wich is not possible with a filled combine. It should be no problem, if you drive it by yourself and press H. If you want to to driv to the field by yourself, then make sure the combine is empty. If the combine is empty and it still does not work, do like @pvaiko turn on the debugchannels and post the logfile.

Ooh that makes sense, thinking about it. I made a video of the problem to try and demonstrate what was happening to @pvaiko (here: https://streamable.com/t6u7tn ) - I was starting the vehicle a little way before the actual start of the course to make sure it didn't miss anything. I suppose I thought, because it was so close to the start of the course that that short distance wouldn't count as "driving" so it didn't occur to me that that was why it was folding stuff.

**Comment by pvaiko** [comment] 2021-12-25 16:37
So, can we close this?

**Comment by ph1go** [comment] 2021-12-25 17:17
Sure, I guess. Autodrive can drive without folding implements so maybe it'd be an idea to have CP make a decision on whether to fold or not based on how close to the start of the course the driver is. If it has to drive miles to get to the field then fold but if the nearest point is like 10 metres directly in front then just pull forward and start working.

**Closed** 2021-12-25 17:20 UTC
Labels: waiting for User
