### ISSUE TITLE
[BUG_SP] Merge Maxx 950 Work width

### ISSUE THREAD

**Issue by enderwiggin07** [Courseplay/Courseplay_FS22#1947] opened 2022-09-28 10:13 UTC
**Steps to reproduce**
Generate course with Merge Maxx 950 windrower, work mode center

**Actual behavior**
Automatically detects width of 10.7m which is too wide for center work mode

**Expected behavior**
Description shows width of 9.5m but effective work width appears to be about 10.3m 

**Courseplay version**
7.1.0.4

**Vehicles/ implements involved**
Merge Maxx 950
Mod no

**Comment by Tensuko** [comment] 2022-09-28 10:38
If the work width is not fixed and changes with tool settings, then you can always change it ingame to the one you need.
Not a bug. Won't fix.

**Closed by Tensuko** 2022-09-28 10:38 UTC
Labels: bug

**Comment by enderwiggin07** [comment] 2022-09-28 11:03
Ok, I would make the argument that the center work mode is the one that CP users will use, because if you make the swath left or right, there is no CP course for the baler that follows that.  So the center work mode should be the one that works correctly with CP.
