### ISSUE TITLE
[BUG_SP] Error: Running LUA method 'update' - Course.lua:448: attempt to index a nil value

### ISSUE THREAD

**Issue by Albatrozs112** [Courseplay/Courseplay_FS22#1477] opened 2022-04-26 11:58 UTC
When i start grape course this show up.
Error: Running LUA method 'update'.
C:/Users/ASUS/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/scripts/Course.lua:448: attempt to index a nil value

**Courseplay version**
Version used: Version: 7.0.1.13

**Log**
error line 1324
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/8562836/log.txt)

**Vehicles/ implements involved**
Vario/587 with DISC-O-VIGNE V

On regular field 
![Bez nosaukuma](https://user-images.githubusercontent.com/79331061/165293140-389b97af-793d-4b77-bf29-ba5ccc38bacc.png)

**Comment by Tensuko** [comment] 2022-04-26 14:32
You also got a Callstack:
```
2022-04-26 14:41   Error: Invalid self object given for SpecializationManager.addSpecialization. Usage: 'g_specializationManager:addSpecialization(name, className, filename, customEnvironment)'
2022-04-26 14:41 LUA call stack:
  dataS/scripts/mods.lua (391) : printCallstack
  =C:/Users/ASUS/Documents/My Games/FarmingSimulator2022/mods/FS22_adjustWorkingSpeed/adjustWorkingSpeedRegister.lua (11) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
2022-04-26 14:41   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2022-04-26 14:41 LUA call stack:
  dataS/scripts/mods.lua (396) : printCallstack
  =C:/Users/ASUS/Documents/My Games/FarmingSimulator2022/mods/FS22_adjustWorkingSpeed/adjustWorkingSpeedRegister.lua (11) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (347) : source
  dataS/scripts/mods.lua (839) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (836) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (754) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1152) : update
```

**Comment by pvaiko** [comment] 2022-04-26 14:45
Duplicate of #1412

**Closed by pvaiko** 2022-04-26 14:45 UTC
Labels: bug

**Comment by Albatrozs112** [comment] 2022-04-26 16:45
> Duplicate of #1412

What no do?
