### ISSUE TITLE
[BUG_MP] Headland overlapping on custom fields generate wrong path

### ISSUE THREAD

**Issue by DrewCZ** [Courseplay/Courseplay_FS22#2898] opened 2023-10-24 21:16 UTC
**Steps to reproduce**
1. define the custom field - map Somewhere in Thuringia III, the position of the field is visible on pic1
2. create a path for wide spreader
3. headlands overlapping in the bottleneck
4. also created paths between overlapped headlands - see pic1

**Actual behavior**
helper is out of field borders - see pic2

**Expected behavior**
in the bottleneck must be reduced number of headlands and unable to create the paths between overlapped headlands

**Screenshots**
pic1 
![obrazek](https://github.com/Courseplay/Courseplay_FS22/assets/26751314/ff939bc7-0626-4a61-818a-2d03eac5220d)

pic2
![obrazek](https://github.com/Courseplay/Courseplay_FS22/assets/26751314/9fd21d7f-a516-44de-b80b-06da1e5b49db)

**Courseplay version**
Version used: 7.3.1.3

**Client Log**
not related

**Server Log**
on request

**Player on the server**
2

**Dedicated server or local hosted server**
Dedicated server = no

**Map**
Somewhere In Thuringia III

**Vehicles/ implements involved**
FS22_Fendt800_900Favorit + FS22_ANNABURGER_HTS_22_79_MultiLandPlus
Mod yes + yes

**Relevant script mods**
FS22_AutoDrive.zip
FS22_BetterContracts.zip
FS22_Configure_Maintenance.zip
FS22_Courseplay.zip
FS22_EasyDevControls.zip
FS22_easyChangeTransmissionType.zip
FS22_MaizePlus.zip
FS22_PowerTools.zip
FS22_precisionFarming.zip
FS22_VehicleControlAddon.zip
VehicleInspector.zip

**Comment by Tensuko** [comment] 2023-10-25 07:09
Both logs are needed!
Always.

**Comment by pvaiko** [comment] 2023-10-26 10:31
The generator should have thrown an error in this case (when the outermost headland overlaps itself), the fact that it did not may be because of https://github.com/Courseplay/CourseGenerator/issues/21. 

The expected behavior is reasonable but it requires an effort vastly unproportionate to the benefits. Won't fix.

**Closed by pvaiko** 2023-10-26 10:31 UTC
Labels: bug, waiting for user, multiplayer

**Comment by DrewCZ** [comment] 2023-10-26 20:39
@pvaiko do you need logs anyway? Im out of pc until monday 30.10.

**Comment by pvaiko** [comment] 2023-10-27 21:26
No need for the log, thank you!
