### ISSUE TITLE
Tractore does not stick to turn in turn manuver.

### ISSUE THREAD

**Issue by svencorell** [Courseplay/Courseplay_FS22#65] opened 2021-12-25 08:32 UTC
Reproducible issue with field "escaping" (version 7.0.0.3):

![20211225093008_1](https://user-images.githubusercontent.com/10363648/147380973-2d034b22-aa74-4a79-b65a-ee5a0544d6bc.jpg)

During turn to the second row, a temporary path with more than 120 Nodes has been created and after the firs 16 oder 17 nodes the escape begun.

Log: https://pastebin.com/AjQ0nNTg

**Comment by pvaiko** [comment] 2021-12-25 14:50
Could you post the entire log? Or at least back about a minute before the one you posted starts?

**Comment by svencorell** [comment] 2021-12-25 17:48
updated log: https://pastebin.com/LwNAmUf0

**Comment by Geradsralf** [comment] 2021-12-25 21:33
Hallo, habe das gleiche Problem beobachtet. Beim Grubbern Feld 12 3 Reihen Vorgewende und dann spiralförmig. Die Vorgewendereihen funktionieren. Dann erste kurze Bahn klappt. Beim grünen Wegpunkt zum Umsetzen auf die nächste Reihe kommt der Fehler, Das Fahrzeug driftet einfach ab und fährt in einem nicht näher bestimmbaren Winkel immer weiter, über Straßen, Nachbarfelder, etc. Der Fehler war in meinem Fall reproduzierbar. Manuell an der nächsten Reihe angesetzt und beim nächsten grünen Wegpunkt kam der Fehler.
[log 2021_12_25 22_22.txt](https://github.com/Courseplay/Courseplay_FS22/files/7776290/log.2021_12_25.22_22.txt)

**Comment by pvaiko** [comment] 2021-12-29 00:39
@Geradsralf that should already be fixed in the later versions.

**Comment by pvaiko** [comment] 2021-12-29 00:39
@svencorell I can't reproduce this. If this is a standard map, could you tell me which one and save the course and post it here?

**Comment by svencorell** [comment] 2021-12-29 06:45
@pvaiko Peter, I can't reproduce this with 7.0.0.9. This was on Elmcreek, Field 39. There are still some issues with the used 4905 Blue Drive (extreme large turn radius vs. smaller planned turns). Maybe that was the cause for the escape.

**Comment by Geradsralf** [comment] 2021-12-29 08:17
Thanks for your answer, I did not see this bug since updating courseplay.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Peter Vaiko ***@***.***> Datum: 29.12.21  01:39  (GMT+01:00) An: Courseplay/Courseplay_FS22 ***@***.***> Cc: Geradsralf ***@***.***>, Mention ***@***.***> Betreff: Re: [Courseplay/Courseplay_FS22] Tractore does not stick to turn in
  turn manuver. (Issue #65) 
@Geradsralf that should already be fixed in the later versions.

**Closed** 2021-12-29 12:12 UTC
