### ISSUE TITLE
[BUG_SP]  Windrower/Baler Combos Fail to take Sharp Turns

### ISSUE THREAD

**Issue by RobTomcat** [Courseplay/Courseplay_FS22#1863] opened 2022-08-20 15:10 UTC
Steps to Reproduce and Actual Behaviour

Using the new integrated Windower/Baler combos eg Claas Quadrant 5300 + Lizard R90 or Krone Big Pack + Lizerd R90, CP will not usually take sharp corners - sometimes it does, sometimes it doesn't.  The tractor (Deutz-Fahr 7 or John Deere 8R) can just stop before reversing to take the corner, it can reverse and then stop before taking the corner, or it can reverse, go forward and take the corner and reverse and then stop without going further.  This happens with CP v 7.1.0.1, 7.1.0.2 and 7.1.0.3 and anywhere on the map.  Rounded corners are no problem.

Expected Behaviour

I expect sharp corners to be taken as normal.

Map Played on

Greenlands, Maypole

Vehicles

As above

**Comment by Tensuko** [comment] 2022-08-20 15:24
I have no Idea what all this is....
Why did you throw away the tamplate?
We have that for reasons and also a screenshot section.....

**Comment by RobTomcat** [comment] 2022-08-20 15:42
I have explained what happens pretty clearly so I have no idea why you do not know what it is all about.

**Comment by Tensuko** [comment] 2022-08-20 15:50
Screenshots!

**Comment by RobTomcat** [comment] 2022-08-21 13:46
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Using the new integrated Windower/Baler combos eg Claas Quadrant 5300 + Lizard R90 or Krone Big Pack + Lizard R90, CP will not always take sharp corners - sometimes it does, sometimes it doesn't.  The tractor can just stop before reversing to take the corner, it can reverse and then stop, or it can reverse, go forward and take the corner and reverse and then stop.  

**Actual behavior**
In the example game with log file attached:

Game started and turned debug on through  Easy Development Controls.  

Created CP course for windrowing/baling with lots of 90 deg turns starting in the centre.  The first few 180 deg turns went fine as always. First 90 deg turn ok,  2nd 90 deg turn tractor turned, reversed to get on course and stopped with engine running and implements raised, would not go forward (Turn 1 pic).  Restarted tractor moving.

Next few rounded and 90 deg turns ok.  Then 90 turn, no reverse and stop with engine running and implements raised (Turn 2 pic).  Restarted tractor moving.

A couple more good 90 deg turns, then 90 deg turn and stop, no reverse, engine running and implements raised (Turn 3 pic).

Stopped and saved game.

**Expected behavior**
I expect the windrower/baler combo to take all 90 deg turns correctly as it takes 180 and rounded turns.

**Screenshots**
Sorry, screenshots took double screens.

Turn 1
![Turn 1](https://user-images.githubusercontent.com/99221276/185793409-48269c85-66b9-49e7-bee9-389558ffeff2.png)

Turn 2
![Turn 2](https://user-images.githubusercontent.com/99221276/185793424-b841206c-cfd5-4486-8cd5-411a9569ef9c.png)

Turn 3
![Turn 3](https://user-images.githubusercontent.com/99221276/185793437-51779828-2888-41c2-abf3-a66843083c76.png)


**Courseplay version**
Version used: CP v 7.1.0.3 but the bug also occurred with v 7.1.0.1 and 7.1.0.2

**Log**
  log.txt (https://gist.github.com/RobTomcat/92cd8f883919aa94be7ae4a6dbd928e9)  log.txt

**Map**
Greenlands

**Vehicles/ implements involved**
Deutz-Fahr 9340 TTV with integrated Krone Big Pack + Lizard R90 but the problem occurs with any large tractor and windrower/baler combo.
Mod Yes

**Relevant script mods**
Although I have Autodrive or VCA installed, these were not activated.


Hope all this is the information you require.
Rob

**Comment by Tensuko** [comment] 2022-08-21 13:55
> Game started and turned debug on through Easy Development Controls.

Easy Dev Controls does not turn on debug for Courseplay. That is done in the vehicle settings at the bottom.


> Next few rounded and 90 deg turns ok. Then 90 turn, no reverse and stop with engine running and implements raised (Turn 2 pic). Restarted tractor moving.

If you would not hide the info panel in the bottom left corner, that would provide already more informations I am pretty sure....


> Sorry, screenshots took double screens.

Hit the print screen on keyboard and your ingame screenshots are in ..\My Games\FarmingSimulator2022\screenshots


If you check your logfile, you got mods with Errors and a callstack at the start and one callstack running all the way till the end.

I can only guess here that when your tractor stops, he got a bale in the back of the baler sticking out a bit?
In that case the info Panel would tell you vehicle is blocked and that is known already, got nothing to do with the turn itself.

**Comment by Tensuko** [comment] 2022-08-21 13:56
#1779

**Comment by RobTomcat** [comment] 2022-08-21 14:37
Thank you for your comments.  I have turned off the info widow bottom left, removed a couple of the mods you pointed out in the log file that were causing issues thank you (I don't normally check the log file), but the problem persists.

In this new pic, again CP is stopped while trying to reverse on a 90 deg corner.  There is no bale "hanging out the end" although one is clearly in the baler output tray, there is no bale on the ground and no message appeared to say vehicle is blocked in any way.

![fsScreen_2022_08_21_16_29_16](https://user-images.githubusercontent.com/99221276/185796203-3a61c98c-72c6-4d0c-a7e2-0ddb93914fbe.png)

**Comment by Tensuko** [comment] 2022-08-21 16:32
> and no message appeared to say vehicle is blocked in any way.

becouse you turned off the info panel......

**Comment by RobTomcat** [comment] 2022-08-21 20:04
I can rerun tomorrow (Monday) with the info panel turned on.  Would it help for you if I also turned logging on  in the Vehicle Settings as you suggested above?

**Comment by Tensuko** [comment] 2022-08-22 06:02
Sure can help with debug logging.

**Comment by RobTomcat** [comment] 2022-08-22 08:21
OK, I have rerun the last part of the baling again with system changes as you suggested.

This time the tractor stalled at the first 90 deg turn it encountered.  It reversed back, went forward and turned, reversed and then stopped as before with engine running and implements raised.

You were correct in your original assessment in that CP now says "Blocked by an Object" but I don't see any object in the way in the image.  There is no bale blocking the tractor starting and there is no bale hanging out the back end of the baler.  Hopefully the log may give you a better idea of the problem.

log.txt https://gist.github.com/RobTomcat/1ebaf5355ba0ed30ba3c68e173d6cb3e 

![fsScreen_2022_08_22_10_03_36](https://user-images.githubusercontent.com/99221276/185873240-70ca4555-8d9a-49fe-8045-0e78677489fa.png)

Rob

**Comment by Tensuko** [comment] 2022-08-22 08:43
It is the bale in the baler that already is somewhat out, I know what the problem is...
Now you got to wait till we find a solution.

**Comment by RobTomcat** [comment] 2022-08-22 10:55
Thanks for the info.  The bale is not hanging over the end of the baler, it is still within the baler output tray but I understand that may be causing the issue.  No problems waiting for a solution and thanks for your attention to this in due course.

Courseplay is a great mod btw and I use it all the time.

Thanks, Rob

**Comment by Resandise** [comment] 2022-11-22 14:10
Wasn't there a similar issue with a cotton baler that was fixed awhile?  Also, when using this baler and this issue occurs, when restarting CP after fixing the turn, it ejects all bales that are completed, which is fine on the second or third headlands, but when its on the first headland, it ejects them off the field and the driver for wrapping/collecting will not find them. Is there a way to at least not eject them when restarting.  Also at the end of the course, it does not eject and fold the baler when fold toosl at course end is activate.

**Comment by bvknight** [comment] 2023-01-05 03:18
When the rectangular baler gets stuck reversing from a bale in the chute, I have been able to fix it by dragging the tractor/baler forward or back a small amount using super strength. The tractor then resumes its course normally, even when reversing. Maybe an automatic "if object blocked when baler reversing, drive forward X distance, then resume course"?

**Comment by k4talin** [comment] 2023-02-26 04:53
So there is no fix yet.

**Comment by k4talin** [comment] 2023-03-04 07:13
> I have no Idea what all this is.... Why did you throw away the tamplate? We have that for reasons and also a screenshot section.....

Maybe bother to take a tractor and a baler do what he explained sharp corners and see. Then u might have an ideea about this issue. Stop asking pictures for anything maybe and open the game to replicate. Players explain more than ewnough the issues

**Comment by Tensuko** [comment] 2023-03-18 19:22
Should be fixed in 7.2.0.4

**Closed by Tensuko** 2023-03-18 19:22 UTC
Labels: enhancement
