### ISSUE TITLE
Generate course missing on balers since 7.0.1.19[BUG_MP]

### ISSUE THREAD

**Issue by Wilco20004** [Courseplay/Courseplay_FS22#1694] opened 2022-06-08 19:40 UTC
**Steps to reproduce**
Hook up a baler (Pottinger Impress 125FC Pro) Click on temporary course and whala no generate button as with any other implement

**Actual behavior**
Button missing unable to generate a path to do baling runs

**Expected behavior**
Generate field course
![image](https://user-images.githubusercontent.com/24457236/172704002-fbb29c6d-4b94-4ffd-9cce-6c31e1722387.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/24457236/172702555-4f4099fc-5fec-4636-b479-f58b97e95fc0.png)
![image](https://user-images.githubusercontent.com/24457236/172703639-ae488dc9-1112-46a5-8924-a27f04f60fd5.png)
![image](https://user-images.githubusercontent.com/24457236/172703812-b7e4162f-4f07-4083-93ca-6b193ffc7fc6.png)
![image](https://user-images.githubusercontent.com/24457236/172703913-5db837eb-636c-4687-a6d4-655e833ce873.png)

**Courseplay version**
Version used: 7.0.1.19 and 7.0.1.20, worked in 7.0.1.18

**Player on the server**
1 - 4 does not matter

**Dedicated server or local hosted server**
Dedicated server yes

**Map**
Map played on. FS22_FM_Map_MountainHill2022

**Vehicles/ implements involved**
Which vehicle or implement? Pottinger Impress 125FC Pro , any tractor
Mod no.

**Relevant script mods**
None

**Comment by Tensuko** [comment] 2022-06-09 03:51
Working as intended.
It doesnt make sence to create a course with a baler, as you wont hit the swath of a combine for example.
Baler always use the course of the other tool worked on the field before

**Comment by Tensuko** [comment] 2022-06-09 04:15
Need to try the baler with swath function (mod).... Forgot about that.

**Comment by Tensuko** [comment] 2022-06-09 16:05
Baler with swath functions is working.
So this will be closed as it is almost impossible to hit the swath correct when generate a course with a baler.
Load the course of the harvester or swather or mower and run it.
Thats what it was made for.

**Closed by Tensuko** 2022-06-09 16:05 UTC
Labels: bug, multiplayer
