### ISSUE TITLE
[BUG_SP] Unloader called at row end although combine far from 80% fill level

### ISSUE THREAD

**Issue by rohne83** [Courseplay/Courseplay_FS22#2373] opened 2023-03-09 15:13 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Combine harvesting with an auger wagon, combine course with headlands and lands pattern (looks a bit strange in screenshot as the field is quite complicated, but also saw it happening on quite regular fields where every land is designed perfectly). Can be reproduced at least for multitool courses. Not tried yet with single tool course. Happening on irregular basis though, but at least on larger fields I experienced it very often lately. Situation occured not for every row turn. In generated logfile it occured at the very end, when last screenshot was taken.

**Actual behavior**
Combine with fill level much below 80% is still calling unloader near row end. In screenshot you see the unloader being called although combine fill level is at 38% only, which of course is much too early. When I then fire the cp helper in combine and/or unloader, maybe perform the turn manually, and only reengage both after the turn completed, it can then happen that unloader ignores this combine completely until it is completely full (so won't try to rendezvous at 80% at all, not even in very long rows).  Suspect this whole behaviour might be unwanted side effect of fix for #2292 ?

**Expected behavior**
The combine calls the unloader for a fill level at rendezvous point of 80%, as originally intended.
Enhancement: If possible, even if calculated rendezvous point with 80% would be at row end indeed, it should be moved to start of next row if there's no fruit under pipe there, to enable unloading on the go and prevent convoys from being stretched out (risk of first combine overtaking last combines especially on irregularly shaped fields).

**Screenshots**
![fsScreen_2023_03_09_15_44_56](https://user-images.githubusercontent.com/71030138/224061649-d2529079-1778-4f4d-be94-1a57c18a255e.png)

**Courseplay version**
Version used: 7.2.0.2

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10932798/log.txt)

**Map**
Landkreis Rostock

**Vehicles/ implements involved**
Which vehicle or implement? Lexion 8900-5300 pack from modhub, any auger wagon.

**Relevant script mods**
N/A

**Comment by pvaiko** [comment] 2023-03-09 17:49
There's not a lot of messages from the combine in the log, are you sure it has the debug turned on? It is usually clear from the logs what it is doing.

Anyway, we have logic in there to call the unloader before turning if the pipe will be in the fruit after the turn at 80% in the next row. So it may well be side effect of #2292, as with multitools all we can do is to check if there is fruit at that location _now_  (which is also logged). 

If you have a better log, we can see if this is the problem. 

Your enhancement idea probably won't work with multitool as we don't know if the pipe will be in fruit after the turn or not.

**Comment by pvaiko** [comment] 2023-03-10 21:55
Yeah, it is in the WAITING_FOR_UNLOAD_BEFORE_STARTING_NEXT_ROW state, but I think the part where it decided what to do and called the unloader is still missing from the log.

**Comment by rohne83** [comment] 2023-03-13 18:12
Nother field, similar situation (end for first row of first land this time). This time I had vehicle debug active all the time for affected combine and unloader. Hope this helps.

![fsScreen_2023_03_13_19_10_21](https://user-images.githubusercontent.com/71030138/224791632-70236425-e2de-47b7-8e27-f73bce60fa00.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/10960409/log.txt)

**Comment by pvaiko** [comment] 2023-03-13 18:54
Yes, it is pretty clear now from the log, the combine thinks it will be full in the next row but at that location, the pipe would be in fruit, therefore brings up the rendezvous point to the end of the current row. 

I can't judge the situation on the field, but most likely this is because with multitool we can't reliably predict if the pipe will be in fruit or not.

So what is the expected behavior? Just skip calling the unloader in this situation when running multitool?

**Comment by rohne83** [comment] 2023-03-13 19:47
> So what is the expected behavior? Just skip calling the unloader in this situation when running multitool?

Might be best workaround. Independent of the pattern for field center, it's only the leading combine where pipe can be in fruit at all (first row of a new land, or every second row when pattern is up/down). For all other combines you can prevent the pipe being over fruit always just be appropriate setting for symmatric/asymmetric row turns.
For long term, I think a mapping of fruit under pipe to waypoints already during course generation might be a way to go (afaik the course generator knows the pipe side, so it can judge whether the waypoints of the row at pipe side have been worked before).

**Comment by kwguk** [comment] 2023-03-16 18:10
Im getting the same thing, though when my combine restarts it leaves a strip of uncut corn. I seem to recall in previous FS CP versions when a combine restarted it backed up a little bit so as to avoid missing any crop on restart,
![20230316172640_1](https://user-images.githubusercontent.com/11178621/225713294-e6969702-149d-45de-9d7a-1701840cd6b0.jpg)

**Comment by Tensuko** [comment] 2023-03-21 09:17
That left over corn I had never happened.
You use any mod that manipulates combine or driving?

**Comment by kwguk** [comment] 2023-03-22 14:27
> That left over corn I had never happened. You use any mod that manipulates combine or driving?

None at all. It tend to only do it when the combine stops below 80%

**Comment by rohne83** [comment] 2023-04-01 15:00
So think best approach would be if you can determine whether combine is the leading one of the multitool convoy or a trailing one (maybe by current waypoint?):
a) if leading combine, same applies as for single tool course: if rendezvous point will have fruit at 80% rendezvous point then move rendezvous point to end of current row (think you're doing this already)
b) for all others (they should never have fruit under there pipe regardless of pattern for field center) only meet with unloader at 80%, never check whether there will be fruit there. And enhancement: if rendezvous point is at very end of current row, move it forward to the start of the next row.
If there's no way to determine the order of the combines on the course, then workaround would be to ignore the fruit check for all combines of multitoolcourses. This will affect the leading combine, but only this one. While all others will be handled at the correct time.

**Comment by rohne83** [comment] 2023-04-02 14:56
Another thing closely related to this issue currently is, as already described in opening post:
If I disengage the unloader since it wanted to go to the combine much too early, and reengage it later again, it often happens that it won't drive to that combine again at all (only if it got completely full).
"2023-04-02 16:43 :19 [dbg1 lp310549] LEXION 7700/984: WORKING: Pipe would be in fruit at waypoint 2183. Previous row is already started, no rendezvous
2023-04-02 16:43 :19 [dbg1 lp310549] LEXION 7700/984: WORKING: callUnloaderWhenNeeded: can't find a good waypoint to meet the unloader!"
Could track it at the very end of this logfile.
![fsScreen_2023_04_02_16_43_58](https://user-images.githubusercontent.com/71030138/229360647-3a71376c-886a-4b45-b134-10c73480a192.png)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/11132530/log.txt)

**Comment by pvaiko** [comment] 2023-04-02 15:33
> for all others (they should never have fruit under there pipe regardless of pattern for field center)

This is true (assuming pipe on the left side) as long as the leader is the leftmost one, next is the second to left etc., last is the rightmost one, otherwise not necessarily true, or am I missing something here?

**Comment by rohne83** [comment] 2023-04-03 14:49
> > for all others (they should never have fruit under there pipe regardless of pattern for field center)
> 
> This is true (assuming pipe on the left side) as long as the leader is the leftmost one, next is the second to left etc., last is the rightmost one, otherwise not necessarily true, or am I missing something here?

I'd say always. If the pipe is on the right side, you will just change the order (first combine/harvester rightmost, then center then left) and you have the same again that all trailing harvesters have the pipe outside the fruit every single lane. So it's always only the first harvester where the pipe inside/outside fruit question is relevant.

**Comment by pvaiko** [comment] 2023-06-02 11:45
@rohne83 can you check if it is better with #2573 ?

**Comment by rohne83** [comment] 2023-06-02 18:34
Quick test on 15hectars with 2 combines was working well. Didn't see this behaviour anymore.
Of course, if I understand the code correctly, this means that first combine won't wait at row end anymore when he has fruit on pipe side at the next row - but fortunately this situation occurs much less often than the wrong behaviour before. So is a great improvement already.

**Closed** 2023-06-28 11:35 UTC
Labels: bug
