### ISSUE TITLE
[BUG_SP] Hardi Aeon 5200 bouncing

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#546] opened 2022-01-16 09:51 UTC
**Steps to reproduce**
Make a course with an Hardi Eon 5200 30m width

**Actual behavior**
the arms are bouncing for no reason, only happen with CP course
if used manually, it doesn't do that

**Screenshots**
https://drive.google.com/file/d/1GR_mtI3Jj-A5BL9ZextEEEK_L4UH1PVx/view?usp=sharing

**Courseplay version**
Version used: 7.0.0.19

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7876679/log.txt)
debug activated near the end of log

**Map**
Erlengradt

**Relevant script mods**
Autodrive 2.0.0.3

**Comment by Tensuko** [comment] 2022-01-16 11:21
Are you sure it comes from CP ?
I can run it without a problem.

**Comment by Chico0008** [comment] 2022-01-16 14:01
Yes, without CP, no probem
with CP driver, arms are jumping

i had another hardi : the 1200l with front reservoir, no problem
haven't tried yet with the 2 other (Hardi 4600 and the last one)

**Comment by ve3jec** [comment] 2022-01-16 15:20
I just reproduced this on Erlengradt 
Fendt 930, Aeon 5200, Liquid fert, field 19
only mods in the folder is CP 
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7877229/log.txt)

**Comment by Tensuko** [comment] 2022-01-16 15:32
And does it happen only on some fields or only when CP drives it or also when you drive it ?
There is nothing I can imagine that make the tool bump arround like that.... at least not from CP.

**Comment by ve3jec** [comment] 2022-01-16 15:51
I just noticed i am using the 27m version of the Aeon 5200 not the 30m as Chico0008 used. 

Tested with F20+CP and still jumps around
Tested with F19+Cp in Hardi Rubicon 9000 no issue
Tested with F20 +CP in Hardi Rubicon 9000 using course generated in fendt with Aeon 5200 no issue
Tested with F19, F20 self drive in Fendt and Aeon 5200 no issue
Tested all other pulled/attached sprayers on F19 without issues its just the Aeon 5200 that wants to twerk 

I zoomed in and watched the jumping and its not the main frame that the tank and wheels are on its the boom mount frame twisting on its lowering mount section. not that that is overly helpful.

**Comment by Tensuko** [comment] 2022-01-16 16:05
Thanks for testing, will see if we find out anything but this is rly not super important...

**Comment by Crinouche** [comment] 2022-03-07 14:37
I have the same problem with Aeon 5200 - 27meter in No Man's Land. If i don't use CP, i have no problem.
With others sprayers. I have no problems.
It's not important for me. I want just to inform you.

**Comment by Tensuko** [comment] 2022-03-26 15:07
Still strange what happens there.
If we could identify one tool one one vanilla map that does it at the same spot, we could see whats happening...

**Comment by Tensuko** [comment] 2022-05-16 16:15
I watched that tool for a while now and could not see any problem....
Maybe it was a problem on Giants side, not sure, but I also don't have any Idea why CP should be responsable for a tool bouncing, since we just unfold it, turn it on, lower it and drag it behind us...

Will close this Issue as not reproducable.

**Closed by Tensuko** 2022-05-16 16:15 UTC
Labels: bug, low priority
