### ISSUE TITLE
Speed settings affects all vehicles

### ISSUE THREAD

**Issue by Nordvarg** [Courseplay/Courseplay_FS22#113] opened 2021-12-26 09:40 UTC
Dear dev team - Thank you so much for your hard work on this magnificent mod.

Using v7.0.0.4, it seems tweaking the speed settings (fieldwork, field, turn, reverse) apply to all vehicles, not only the one I'm inside. 

When I switch to another vehicle and adjust the settings again, all vehicles get those settings, as well. 

(I've tested it on a new game save with CP being the only mod.)

**Comment by pvaiko** [comment] 2021-12-26 11:32
Duplicate of #58

**Comment by pvaiko** [comment] 2021-12-26 12:30
The actual settings do not change for all vehicles, if you look at the list header, you'll see the same vehicle. 

The problem is that the settings list is not always updated when you tab to a new vehicle, it shows the data for the same vehicle.

**Comment by Tensuko** [comment] 2021-12-26 13:59
Pls test 7.0.0.5 and report :)

**Comment by pvaiko** [comment] 2021-12-27 00:50
Not sure if we need to do anything about this. The CP vehicles settings shown are for the vehicle which is selected in the Giants helper UI page, which is not the vehicle you are in, but the one last selected.

**Comment by Tensuko** [comment] 2021-12-27 17:52
Seems to be fixed now.

**Closed by Tensuko** 2021-12-27 17:52 UTC
Labels: waiting for User
