### ISSUE TITLE
[BUG_SP] Reverse driving has a activated debug by default

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/Courseplay_FS22#397] opened 2022-01-06 22:28 UTC
**Steps to reproduce**
Create a field work course and wait until the vehicle needs to drive backwards, e. g. in order to make a turn.

**Actual behavior**
When the reverse gear is engaged, a red line (behind tractor) and a yellow writing (above the steering wheel) will show up, but it flashes constantly. This happens with debug channels shut off.

**Expected behavior**
With debug channels deactivated, reverse driving should not show the flashing red line and yellow writing

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/47073128/148460594-094267ab-ed96-4f63-83ab-174945931242.png)
The red line and the yellow writing flashes.

**Courseplay version**
Version used: 7.0.0.16

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7825062/log.txt)

**Map**
Doesn't matter, happens on every map

**Vehicles/ implements involved**
Doesn't matter, happens with every tool

**Relevant script mods**
AutoDrive ist installed, but not involved in this case

**Comment by pvaiko** [comment] 2022-01-06 22:38
Duplicate of #394, and already fixed on the main branch

**Closed** 2022-01-06 23:02 UTC
Labels: bug
