### ISSUE TITLE
[BUG_SP] Amazone Sowing Machine reverse driving results into fail

### ISSUE THREAD

**Issue by StefanBraun2001** [Courseplay/Courseplay_FS22#196] opened 2021-12-28 09:39 UTC
**Steps to reproduce**
Use CP with the Amazone Sowing machine

**Actual behavior**
Sometimes reverse dring results into tractor and sowing machine becoming wedged

**Expected behavior**
Reverse driving should work as normal with that machine, it is very easy to drive this sowing machine in reverse.

**Screenshots**
![Screenshot (7)](https://user-images.githubusercontent.com/47073128/147552224-592f6302-1110-4814-80f2-64ecc3741a3a.png)

**Comment by XPiRiJenZ** [comment] 2021-12-28 12:12
Duplicate of #93 #173 I think...

**Closed** 2021-12-28 12:13 UTC
Labels: bug
