### ISSUE TITLE
[Question] Sometimes getting following error

### ISSUE THREAD

**Issue by rooymans** [Courseplay/Courseplay_FS22#728] opened 2022-01-27 10:59 UTC
I don't want to raise this as a bug yet, as I have not managed to identify a pattern as to how to reproduce this, but I am getting the following error every now and then (more often than not):

2022-01-27 11:15 :00 [dbg17 lp17918] Course generator returned status false, ok [........] FS22_Courseplay/scripts/courseGenerator/headland.lua:318: attempt to index a nil value, course nil

It happens with the Kverneland Fertilizer Spreader on almost every field. I think it might be related to the lane offset or multitool, because it only happens in version .23 of courseplay. If I play around with the settings a little, especially the alignment setting (auto, longest or manual), then I see the lane offset change from centre to left(1) and after a while, it does generate a course. But then the next field fails again with the above error.

Do you have any idea what might cause this?

**Comment by pvaiko** [comment] 2022-01-27 11:14
If you attach the full log we may be able to answer your question.

**Comment by rooymans** [comment] 2022-01-27 11:17
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7949945/log.txt)

The example above is in line 3300 of the attached log.

**Comment by pvaiko** [comment] 2022-01-27 11:26
You have multitools set, is that intended? I see 4 and 5, which, with this spreader with 40 meters width results in 80 and 100 meter wide headlands.

The generator aborts if the innermost headland won't fit in the field (the area within the innermost headland is 0), this is often the case on In smaller or irregular fields with very wide headlands and certainly is the case here as the message in the log clearly states.

If you did not intentionally set multitools, then this is a duplicate of #715.

**Closed by pvaiko** 2022-01-27 11:26 UTC
Labels: question

**Comment by rooymans** [comment] 2022-01-27 11:50
I have never (at least in FS22) intentionally set multitools to anything different than 1.
And I am unable to reproduce the issue in #715.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7950115/log.txt)

Please find attached a 'clean' logfile with Multitools set to 1 and the error still occurs.
I am suspecting maybe a mod clash somewhere and I will investigate further.

**Comment by pvaiko** [comment] 2022-01-27 11:57
Then it is usually a map problem. Reduce the work width until it generates and then post a screenshot here from the generated course.

**Comment by rooymans** [comment] 2022-01-27 12:11
You're right. At 20.3M it still gives an error and at 20.2M is generated a course.

![Screenshot (4)](https://user-images.githubusercontent.com/56227140/151356355-d5456a75-796a-43a5-b9ad-be782f8d4ea9.png)

**Comment by pvaiko** [comment] 2022-01-27 12:26
Right, that seems to be a very narrow field compared to the work width, some combinations of working width/headland/pattern may not work on it.

**Comment by rooymans** [comment] 2022-01-27 12:39
I can now also reproduce the defect #715 where the multiTool setting automatically changes to '2' instead of '1'. If I load my savegame and select the field 22 on the screenshot above, the multiTool setting automatically goes to '2', but where I select field 21, it remains '1'. Does that help you?

**Comment by pvaiko** [comment] 2022-01-27 12:59
Sure it does, thanks. @schwiti6190
