### ISSUE TITLE
[BUG_SP] Tractor jackknifing at sharp headland corners

### ISSUE THREAD

**Issue by HC1Gunner** [Courseplay/Courseplay_FS22#2054] opened 2022-10-29 23:52 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.

**Actual behavior**
A clear and concise description of what happen.

**Expected behavior**

**Screenshots**

**Courseplay version**
Version used: 

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.

**Vehicles/ implements involved**
Which vehicle or implement?
Mod yes/no ?

**Relevant script mods**
Mods like Autodrive or VCA and so on.

This happen on all maps with every implement I use, and has been going on for the last several versions of CP. If you create a course, choose headland with the "sharp" option, CP jackknifes at every corner of the field, can can't complete any headlands.

When creating a course, you choose to do Headlands and select the Sharp option.
1. The vehicle and implement complete the pass stopping short of the field edge.
2.  CP starts forward into a right turn to line up on the headland.
3.  But way before it gets straightened out, CP starts backing up towards the line (pass) it just completed.
4.  CP continues in a rear right turn, and jackknifes the equipment, at this point CP appears to be lost.
5.  Now it just stays jackknifed, and spins in reverse forever.

CP fails at all (4) corners to at 90 degree (sharp) headland, for has many headlands as was requested.

Haut-Beyleron - Giants base-game map.

All Giants stock equipment, no mods being used equipment wise. John Deere 7R, and Lemken KORALIN 9-840

Easy Dev Controls, and AutoDrive are loaded, but not in use.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/9894776/log.txt)

![Headland Sharp 1](https://user-images.githubusercontent.com/45585444/198856189-aa6a2316-2594-4e6e-b9c0-2a8717929d6d.jpg)

![Headland Sharp 2](https://user-images.githubusercontent.com/45585444/198856178-b1e68134-1b57-446a-874f-10d445505b2a.jpg)

![Headland Sharp 3](https://user-images.githubusercontent.com/45585444/198856196-21fb1b3f-36e3-416e-a8c6-84ad88f10204.jpg)

![Headland Sharp 4](https://user-images.githubusercontent.com/45585444/198856201-39aacd03-ed74-4942-9e91-5d55dda69c01.jpg)

![Headland Sharp 5](https://user-images.githubusercontent.com/45585444/198856212-37b6a33e-3521-42bc-afc0-8c7b87e40453.jpg)

![Headland Sharp 6](https://user-images.githubusercontent.com/45585444/198856219-ba368e4d-c853-4110-bbb3-d846f4964e3d.jpg)
![Headland Sharp 7](https://user-images.githubusercontent.com/45585444/198856227-2ecd4f17-1cc4-4d92-8693-091393089eb0.jpg)

v7.1.1.5, but the same issue existed with several of the previous versions.

**Comment by Tensuko** [comment] 2022-10-30 07:24
With debug on it should have been better, but I have a look.

**Comment by Tensuko** [comment] 2022-10-30 08:22
Can't reproduce:
![fsScreen_2022_10_30_09_22_07](https://user-images.githubusercontent.com/27344744/198869245-521463dd-48bc-4486-a87e-4c5f5833138b.png)
![fsScreen_2022_10_30_09_22_28](https://user-images.githubusercontent.com/27344744/198869250-cf1d1ef1-bcdc-4a55-9652-991e27e5814d.png)

**Comment by Tensuko** [comment] 2022-10-30 08:26
On your screenshot I see at least one more mod, VCA or EnhancedVehicle, not sure wich one it is, guess its 2nd.

**Comment by MeRida2104** [comment] 2022-10-30 09:46
It's EnhancedVehicle.

**Comment by pvaiko** [comment] 2022-10-30 11:13
Looks like CP thinks the tractor has no towed implements, although it finds the Koralin:
```
2022-10-29 19:44 :41 [dbg16 lp9163] 7R 350/155:   Koralin 9-840: using the Giants turn radius 6.7
2022-10-29 19:44 :41 [dbg16 lp9163] 7R 350/155:   Koralin 9-840: max tool radius now is 6.7
2022-10-29 19:44 :41 [dbg16 lp9163] 7R 350/155: getTurningRadius: 6.7 m
2022-10-29 19:44 :41 [dbg9 lp9163] 7R 350/155: No towed implement found.
```

And this line in the VehicleConfigurations.xml should make sure it is detected as a towed implement, so no idea why it is ignoring it:
```
2022-10-29 19:42 :33 [info lp1785] Reading configuration for koralin9840.xml
2022-10-29 19:42 :33 [info lp1785] \__ implementWheelAlwaysOnGround = true
```

**Comment by Tensuko** [comment] 2022-10-30 11:35
> It's EnhancedVehicle.

try without, just out of curiousity

**Comment by Goofy78** [comment] 2022-10-30 16:06
Wenn ich das richtig sehe ist es das selbe Problem wie von Anfang an. Es liegt am Laforge1700 Gewicht was unter dem Traktor hängt. Siehe oben rechts 2 Gewichte am Traktor.

**Comment by Tensuko** [comment] 2022-10-30 16:46
Kann der überhaupt ein Gewicht konfigurieren?
Oben links ist nichts zu sehen, aber mit oben rechts du hast recht....

**Comment by Goofy78** [comment] 2022-10-30 16:59
Das Laforge1700 ist seperat im Shop unter Gewichte.

Es wird auch oben links nicht angezeigt. Ich habs getestet und es funktioniert ohne das Gewicht unten drunter,  aber sobald das Laforge1700 drunter hängt, ist es genau so wie oben beschrieben. Das ist aber schon von Anfang an so. Ich hatte da auch schon ein ISSUE deswegen.

**Comment by Tensuko** [comment] 2022-10-30 17:03
Okay das war mir entfallen, dass es so ging. Ich dachte das wird mit konfiguriert.

Glaub das Issue hatten wir zu gemacht, weil das so eine Ausnahmegeschichte ist.
Ist ja jetzt auch lange nicht mehr gewesen.

**Comment by HC1Gunner** [comment] 2022-10-30 20:17
You don't understand, if you had read everything you would now, it's not just this particular implement.
I have this same problem, with every vehicle, every piece of towed equipment, on every map. This includes everything vanilla (base game), and all mods. This is NOT an isolated incident, not one piece of machinery will do a course created with the option of "sharp" headlands.

Here's the same thing happening with a Kubota tractor, towing about the simplest implement you can get (roller). It can't get lined up to do the headland, starts backing up early, jackknifes, and spins in reverse forever.

![FarmingSimulator2022Game_2022_10_29_00_57_57_142](https://user-images.githubusercontent.com/45585444/198899733-ef7214a5-43b5-40c2-b020-82d39d4c5cc5.jpg)

**Comment by HC1Gunner** [comment] 2022-10-30 20:26
BTW, it's not enhanced vehicle, there are on (3) mods I have loaded, mod folder contains, CP, AD, and Easy Dev Controls. Look at the log, show on these three mods loaded.

2022-10-29 19:42   Load mod: FS22_AutoDrive
2022-10-29 19:42   Load mod: FS22_Courseplay
2022-10-29 19:42 C:/Users/hc1_g/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/img/signs/normal.i3d (0.60 ms)
2022-10-29 19:42 C:/Users/hc1_g/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/img/signs/start.i3d (0.52 ms)
2022-10-29 19:42 C:/Users/hc1_g/Documents/My Games/FarmingSimulator2022/mods/FS22_Courseplay/img/signs/stop.i3d (0.47 ms)
2022-10-29 19:42   Load mod: FS22_EasyDevControls

**Comment by HC1Gunner** [comment] 2022-10-30 21:27
I see what you mean by the screen shots with the extra symbols in the HUD, but...

If you look at the log, it only shows the three I stated being loaded.  Before I started my test on Haut-Beyleron, I deleted the log file, and removed every mod except these three. So all I can say is, there is a bug or glitch somewhere, if Enhanced Vehicle is not in the mod folder, and the log does not show its loaded, then Giants has something weird going on.

**Comment by Tensuko** [comment] 2022-10-30 21:52
As you see on my screenshots with about 290 mods (also a lot of scripts) I dont have any of those problems.
I recommend you a reinstall and clean up settings folders and stuff couse there must be enhanced vehicle active anywhere else it would not have its hud on your screenshots.
There is nothing we can do for you.
Also re download your mods.

**Comment by tn4799** [comment] 2022-10-31 11:26
@HC1Gunner When you test something with other vehicles you should only use a tractor and the tool. Nothing more should be used and attached to the tractor. 
In your later screenshot you attached a tractor triangle to your tractor which caused the same behaviour as the weight plate on the john deere. 
So if you dont attach anything in the back that has no attacher you wont run into this problem until the issue is fixed.

**Comment by pvaiko** [comment] 2022-10-31 11:31
> @HC1Gunner When you test something with other vehicles you should only use a tractor and the tool. 

Or, at least mention that there's something else attached to the tractor too. Or add a logfile, so we can check ourselves.

**Comment by Tensuko** [comment] 2022-10-31 12:03
Especially a real logfile and not a modified one that looks nicer, that doesn't help in finding the real issue especially if the screenshots doesn't match....

**Comment by HC1Gunner** [comment] 2022-11-01 23:15
I finally got enhanced vehicle to stop showing in the HUD by finding and deleting its left-over folders / files, but I still have the issue of CP not being able to do sharp headlands, that leaves Guidance Steering. I use GPS almost every game myself, so if it's the culprit, I'm not going to remove the GPS mod. One would think the someone on the CP team would be clever enough figure out the issue and fix it, when it has just this one conflict.

**Comment by HC1Gunner** [comment] 2022-11-01 23:19
> > @HC1Gunner When you test something with other vehicles you should only use a tractor and the tool.
> 
> Or, at least mention that there's something else attached to the tractor too. Or add a logfile, so we can check ourselves.

I'm not sure why but it's a waste of time to give of this info if you're not going to look, right before my first screenshot its has a hotlink that says...log.txt

**Comment by pvaiko** [comment] 2022-11-01 23:39
Yeah. I saw that, looked at that and it had the Laforge, a known problem. What I was missing is a second log for your second screenshot with the Kubota, where you did not mention that other thing confusing CP (which we still don't know what exactly is).

**Comment by pvaiko** [comment] 2022-11-02 00:12
> One would think the someone on the CP team would be clever enough figure out the issue and fix it, when it has just this one conflict.

No, we are all idiots, doing this, obviously. You probably missed the pull request and the upcoming fix in the next release for your issue.

**Comment by Tensuko** [comment] 2022-11-02 06:53
> One would think the someone on the CP team would be clever enough figure out the issue and fix it, when it has just this one conflict.

Watch your words dude.... locking this Issue now, be happy we have a fix for this with the next Version and next time give the right details!

**Closed** 2022-11-06 10:51 UTC
Labels: bug, enhancement
