### ISSUE TITLE
[BUG_SP] Combine repeatedly misses the first part of all rows (but only in one direction) on one course.

### ISSUE THREAD

**Issue by ph1go** [Courseplay/Courseplay_FS22#280] opened 2021-12-31 12:48 UTC
**Courseplay version**
v7.0.0.10

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796221/log.txt)

**Map**
Elmscreek

**Vehicles/ implements involved**
John Deere X9 1100

The time that the screenshots were taken (13:02) is when the problem happened on this row but it happened on all southbound rows in that field. The course looks fine, there weren't any close obstacles and it looks like there's plenty of room to turn (2 headlands).

![fsScreen_2021_12_31_13_02_09](https://user-images.githubusercontent.com/30246276/147823929-7c05c2b8-3cf3-4448-b2d4-47bb5a640a64.jpg)
![fsScreen_2021_12_31_13_02_20](https://user-images.githubusercontent.com/30246276/147823934-a01a9480-0669-4f2c-8c24-cc41dbb0bbe1.jpg)
![fsScreen_2021_12_31_13_02_27](https://user-images.githubusercontent.com/30246276/147823940-601ca560-c28f-4f97-8105-32e46da73265.jpg)
![fsScreen_2021_12_31_13_02_35](https://user-images.githubusercontent.com/30246276/147823952-6947e077-5e0f-4a8a-bec1-71aa2d3eb489.jpg)

**Comment by ph1go** [comment] 2021-12-31 12:53
Ok, forget what I said about "only one course" - he's just done it again on a different field. It seems to happen every time he has to turn left onto a new row.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/7796243/log.txt)

![fsScreen_2021_12_31_13_50_15](https://user-images.githubusercontent.com/30246276/147824387-04e6ba35-f94e-412f-8179-c45865451e6e.jpg)
![fsScreen_2021_12_31_13_50_30](https://user-images.githubusercontent.com/30246276/147824400-71eccce1-00f8-407b-97fd-37f19afee394.jpg)

**Comment by pvaiko** [comment] 2021-12-31 12:53
Duplicate of #277

**Comment by ph1go** [comment] 2022-01-01 10:29
@pvaiko does this look like the same issue? It's the first time I've seen it with an implement other than the combine and he's doing it on every turn here, not just to the left. It looks like he's not pausing to wait for the implement to lower at the start of every row.

![fsScreen_2022_01_01_11_23_30](https://user-images.githubusercontent.com/30246276/147848527-e77d3e6c-0b54-44c2-bc3e-552663fc5fc3.jpg)

**Comment by pvaiko** [comment] 2022-01-01 13:57
Looks the same and should be fixed on the main branch already.

**Comment by pvaiko** [comment] 2022-01-06 00:46
Closing due to inactivity

**Closed by pvaiko** 2022-01-06 00:46 UTC
Labels: bug
