### ISSUE TITLE
[BUG_SP] Convoy order problem at wider turns

### ISSUE THREAD

**Issue by DemsMani** [Courseplay/Courseplay_FS22#1090] opened 2022-02-23 21:56 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Two Combines in Convoy, 2 Headlands Clockwise, afterwards "fields" with 6 lanes per field. Convoy distance is set to 80m in both combines

**Actual behavior**
At shorter turn distances it seems to work well, but if the combines have to travel further from one lane to the other, the first one drives to the new lane while the second one waits with finishing the old lane. As soon as the first combine arrives at the new lane, it stops and the second one finishes the old lane and also travels to the new lane. Then the second one starts combining again and at this point tries to overtake the first one (collides in most cases) which is still standing in front of the new lane and does not start combining again. 

**Expected behavior**
No order change, the first combine starts working already before the second one arrives at the new lane.

**Screenshots**
https://youtu.be/Kt5zuY6erMk

**Courseplay version**
Version used: 7.0.1.2

**Log**
(https://gist.github.com/DemsMani/d1463944091712c9fed3051acdaad011)

**Map**
County Line

**Vehicles/ implements involved**
X9 (from ingame Modhub), HD50F Header (vanilla)

Mod yes/no ?

**Relevant script mods**
Autodrive for the unloader

**Comment by pvaiko** [comment] 2022-02-24 00:02
Duplicate of #902

**Comment by DemsMani** [comment] 2022-02-24 07:00
Sorry, didn't see that this is a duplicate as #902 looked quite different for me, but it could of course be the same issue

**Comment by Tensuko** [comment] 2022-02-28 08:31
Part of Update 7.0.1.3

**Closed by Tensuko** 2022-02-28 08:31 UTC
Labels: bug
