### ISSUE TITLE
[BUG_SP] JD 7R + Laforge EZ 1700 - turnarounds on fieldwork will fail

### ISSUE THREAD

**Issue by IseOlen** [Courseplay/Courseplay_FS22#1306] opened 2022-04-01 02:09 UTC
**Steps to reproduce**
Ingame Laforge EZ 1700 is a special option for 7R only - this weight is attached under the tractor.
Attach the special weight option to 7R, then an implement at the back (tested with seeder Amazon 15001, planter Tempo L16 and some cultivator).
Create a field course (tested with 2 or 3 headlands first).
Run the course. In case the field edge is at an (relatively sharp) angle to the up-and-down lines, the turnaround sometimes succeeds. In case the field edge is anywhere close to 90degrees to the up and down lines, the tractor will end the line, raise implement and starts backing up, indefinitely (usually "scissors up" rather fast).
So somehow this special weight option interferes with CP turnarounds - running the same course with the same implement minus the weight option will work absolutely fine.

**Courseplay version**
Version used: 7.0.1.7 (the issue IS NOT specific to this version - at least couple of earlier versions that I tested had the same issue)

**Vehicles/ implements involved**
Ingame JD 7R + Laforge EZ 1700 + seeder/planter 
Yes, I do have mods installed (including Autodrive) but since without the special weight option everything worked absolutely fine I doubt any conflicts with those.

**Comment by Tensuko** [comment] 2022-04-01 05:48
Becouse that is just a special option, we ignored it for now, as it makes things much more complex just becouse of this weight...

**Comment by IseOlen** [comment] 2022-04-01 06:42
No problem, I can do the fields without the special weight. Took me couple of hours to get to the culprit in this case.

**Comment by pvaiko** [comment] 2022-04-01 10:43
Seems to be a duplicate of #1272.

https://github.com/Courseplay/Courseplay_FS22/pull/1278 should have fixed is, will be in the next release. Reopen if not.

**Closed by pvaiko** 2022-04-01 10:43 UTC
Labels: bug
