### ISSUE TITLE
[BUG_SP] Track Tractors Turning

### ISSUE THREAD

**Issue by squishey123** [Courseplay/Courseplay_FS22#373] opened 2022-01-06 05:13 UTC
**Steps to reproduce**
Fendt 1151 MT with any large attachment using a hitch (Farmet Konpaktomat 1570 Max for example)

**Actual behavior**
Any tractors that use tracks with a very tight turning radius are unable to use large attachments due to the pathfinder attempting turning maneuvers that are impossible. Side effects are attempting to drag the attachment sideways due to the hitch being locked at its maximum angle. *Especially common on headlands*

**Expected behavior**
Pathfinder would look at the working width of the attachment when calculating the turning maneuver so that it can get aligned without locking the hitch, getting stuck, and deactivating the worker

**Courseplay version**
Version used: v7.0.0.12

**Comment by squishey123** [comment] 2022-01-06 05:17
**Similar note**
JCB tractors with 4 wheel turning are also very susceptible to similar behavior

**Comment by Tensuko** [comment] 2022-01-06 09:38
That have to do with turning radius, not working width.
Duplicate of #267

**Closed by Tensuko** 2022-01-06 09:38 UTC
Labels: bug
