### ISSUE TITLE
Working Width display (number) is wrong

### ISSUE THREAD

**Issue by clubpetey** [Courseplay/Courseplay_FS22#376] opened 2022-01-06 07:50 UTC
Using v7.0.0.12

Big M 450 working width is reported in CP as 6.3m, but the width is actually 10m.  
Amazone ZA-TS-3200 is reported in CP as 26.0m but the width is actually 42m.

In both cases the red box that appears when you toggle the CP vehicle settings display is correct.  Course generation also works correctly when using the calculated number displayed in CP.  Changing the working width to the actual number reported by the shop makes course generation wrong.

Guidance Steering does correctly calculate the width if that helps.

**Comment by schwiti6190** [comment] 2022-01-06 07:57
@clubpetey Hi there, 
could you please use the issue template next time with a log file attached :)

![grafik](https://user-images.githubusercontent.com/58079399/148348614-405ed299-da36-4bcb-93bb-1671ddeb7d93.png)

For the big m 450 i couldn't reproduce this problem.
The Amazone ZA-TS-3200 is the same problem as #348, which will be fixed in the next version :)

**Comment by clubpetey** [comment] 2022-01-06 09:37
Sorry, didn't see the template, here's the relevant log entries for the Big M from my machine.  

2022-01-06 00:41 :58 [dbg20 lp581] BiG M 450: getting working width...
2022-01-06 00:41 :58 [dbg20 lp581] BiG M 450: aiMarkers: left=5.00, right=-5.00 (width 10.00)
2022-01-06 00:41 :58 [dbg20 lp581] BiG M 450: working width is 10.0.

But the screen shot shows the width as 6.2m  But notice that the red box is the correct width of the vehicle.

![image](https://user-images.githubusercontent.com/2221486/148361934-7f2c6477-c31e-4d5f-9594-17eb2b151cd5.png)

If I set the width to 10m in the settings, notice the red box is way too big.

![image](https://user-images.githubusercontent.com/2221486/148362045-e79c4e5a-6b8d-41fe-897b-a78000d84543.png)

**Comment by Tensuko** [comment] 2022-01-06 09:40
your gamesettings are meters or miles ?

**Comment by clubpetey** [comment] 2022-01-06 10:28
dollars/miles/acres

**Comment by Tensuko** [comment] 2022-01-06 10:58
Yea then this is the Problem. #128
Should be fixed in the next Version.

**Closed by Tensuko** 2022-01-06 10:58 UTC
Labels: waiting for User
