### ISSUE TITLE
[BUG_SP] Bale collecting and Wrapping, HUD Target Icon opens wrong AI Job

### ISSUE THREAD

**Issue by coatsy35** [Courseplay/Courseplay_FS22#3012] opened 2023-12-12 21:27 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Fastrac 8330 & Arcusin FSX63.72 as issued by baling contract. Set to find bales in field 104 on Holmewold Farm. Eventually can't find any more bales to wrap or collect keeps saying no path found

**Actual behavior**
Wrapper and tractor and collector and tractor eventually lose their path and can't collect any more bales until you drive around enough and keep pressing the play button, eventually it will find a path 

**Expected behavior**
Wrap bales and collect them without loosing it's path

**Screenshots**
![fsScreen_2023_12_12_21_21_26](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/be5a7313-6196-4e83-9718-970c79fddbf0)

**Courseplay version**
Version used: 7.4.0.1

**Log**
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13653360/log.txt)

**Map**
Holmewold Farm 22

**Vehicles/ implements involved**
Giants Fastrac 8330, Giants Arcusin FSX63.72 and also the Giants Kuhn SW4014

Mod - No

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by googlownik1** [comment] 2023-12-15 11:48
I have the same thing, Ursus 1614 tractor with modhub and Kuhn 4014 wrapper, Zielonka map

**Comment by iCrashMix0** [comment] 2023-12-19 15:58
I have the same problem

**Comment by iljarogoff** [comment] 2023-12-19 18:51
Had the same issue. After downgrading to 7.4.0.0 the issue disappeared. No more "No path found"

**Comment by coatsy35** [comment] 2023-12-19 22:24
Agreed. Latest version is broken for bale collecting and wrapping. I guess it's moving the functions to a new controller something isn't quite right.

**Comment by iljarogoff** [comment] 2023-12-20 04:33
Had it with 7.4.0.0 too few minutes ago, but  I guess it happens not so often. Attached a log (7.4.0.1)
[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13722960/log.txt)

**Comment by coatsy35** [comment] 2023-12-26 18:51
Bale collection on straw bales appears to be working though? I hadn't done nay, but spent a chunk of time today leaving a Accusin collector on straw fields and seemingly worked every time.

**Comment by iljarogoff** [comment] 2023-12-27 08:53
> Bale collection on straw bales appears to be working though? I hadn't done nay, but spent a chunk of time today leaving a Accusin collector on straw fields and seemingly worked every time.

Which map did you try?

**Comment by coatsy35** [comment] 2023-12-27 09:08
I was on Holme Farm

**Comment by Tensuko** [comment] 2023-12-30 11:32
Will be fixed in the next release.

**Comment by coatsy35** [comment] 2024-01-03 22:43
Still seeing issues here with 7.4.0.2. Please see log and screenshot below. Is this because it's near the edge of the field with the other fixes for outside of field pathfinding? I will keep running it in this field of 153 bales. So far it's only done it near the edge

![fsScreen_2024_01_03_22_40_07](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/67f70807-ed6b-4f59-a76a-af2f3ce1a4e7)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13824118/log.txt)

**Comment by coatsy35** [comment] 2024-01-03 22:45
Scratch that, it's now just picked up the bale on the other side after I manually drove out into the open to the left of the pair, it looped back and collected the far side one.

![fsScreen_2024_01_03_22_43_44](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/6b410cbe-6654-466d-bd0f-4ae833c0c918)

![fsScreen_2024_01_03_22_43_46](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/d47032ae-28e9-4974-9be1-91811e38634a)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13824134/log.txt)

**Comment by coatsy35** [comment] 2024-01-07 17:07
Thoughts? happens in middle of field as well, just stops with no path found. Are others seeing the same?

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/13854261/log.txt)

![fsScreen_2024_01_07_17_04_58](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/2409db7d-8930-4bbb-9716-2a83d0911b86)

**Comment by coatsy35** [comment] 2024-03-10 21:52
Can this issue be reopened please as still having issues on most fields since the bale collection function was updated in previous releases or is it on the list to revisit?

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14551886/log.txt)

![fsScreen_2024_03_10_21_47_22](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/860dff64-80b0-4b1a-8449-04d70a003d9a)

**Comment by googlownik1** [comment] 2024-03-12 10:59
Unfortunately, I have the same problem, with the difference that now it appears even in the "harvester" option when collecting chaff

**Comment by coatsy35** [comment] 2024-03-12 11:39
To be honest I have a bigger issue at the moment that a lot of the time I select a ew field location, send the collector their via AD and when it gets their is says it's too far from the field location. I select another field and exit the map but the field location won't move, it stays locked on that field when I view the map again. I then have to restart my game to fix it. Not ruled out a mod conflict yet, but I have no new mods. I will make sure I run with the log on next time to try and catch it and upload.

**Comment by coatsy35** [comment] 2024-03-12 17:51
@pvaiko  this is my log from the vehicle too far away from field. Any idea why i keep getting this as well? the only way to fix it is to exit the game and re enter and it will work. Every time i change field I have to exit the game as no tractor or unloader will work.

![Untitled](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/1e908829-02f3-43cf-a139-a9370e8c6ed6)
![Untitled 2](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/ee41bf81-0ae0-4526-a664-414b34697d79)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14576578/log.txt)

**Comment by pvaiko** [comment] 2024-03-12 18:14
Only the bale finder does this?

**Comment by coatsy35** [comment] 2024-03-12 18:20
> Only the bale finder does this?

Yes. I can’t fathom it. It’s like the field position won’t save. Shows that it has but if out go back to map it hasn’t. Exit game and renter, field position is set as the old field. Change it again and it’ll stay and it will work.

**Comment by pvaiko** [comment] 2024-03-12 18:23
The log shows you tried many times:
```
2024-03-12 17:35 :14 [courses lp597489] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :15 [courses lp597543] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :16 [courses lp597585] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :17 [courses lp597620] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :19 [courses lp597711] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :21 [courses lp597772] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :23 [courses lp597860] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :25 [courses lp597978] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :28 [courses lp598117] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :33 [courses lp598330] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:35 :52 [courses lp599141] Fastrac 4220/341: FieldScanner: Start scanning field 30 at 105.8/-1244.5
2024-03-12 17:36 :06 [courses lp599791] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:36 :10 [courses lp599971] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:36 :11 [courses lp600026] Fastrac 4220/341: FieldScanner: Start scanning field 30 at -86.1/-1256.0
2024-03-12 17:36 :16 [courses lp600252] Fastrac 4220/341: FieldScanner: Start scanning field 30 at 105.8/-1244.5
```
twice at the position your screenshot shows, which is on 31 but the log says 30. What I'd like to know is where was the field position at the other tries and which field (30 or 31) was highlighted?

**Comment by coatsy35** [comment] 2024-03-12 18:59
Field 31 was selected always on every try. But when I went back into the menu, the field changes back to 30 which is where it was working ok and finished the job. I’ve also tried setting a new field position and sending the collector their via AD with CP activated. It gets to the field and just sits at the field entrance not doing anything, if I manually press play it then starts bringing up the not near field. I then make sure it’s set which it won’t or is set but still won’t activate. Thinking about it the only update of mods I’ve had lately was the latest AD last week. Wonder if that’s interfering, I can’t recall what they updated. However it still does it if I manually drive to a new field and try

**Comment by coatsy35** [comment] 2024-03-12 19:35
@pvaiko also dropped you latest bug fix into my copy a few hours ago and set another collector running, it has been running for some time and then stopped with no path found. Large log file below, I had to put it in my google drive folder. Might be of interest to you. I will try and geta clean log for the field position error when I get a min

https://drive.google.com/file/d/1lm5PW3QWbxgo8EXupYri0IUJP91h-eZO/view?usp=sharing

![fsScreen_2024_03_12_19_31_54](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/5356863d-6556-42ee-ba03-93ea1dea4d44)

**Comment by pvaiko** [comment] 2024-03-12 20:16
In the first scenario it should have detected the bale in front and backed up, that was a regression I introduced in one of my commits.

Also, keep in mind it does not pick the closest one in the absolute sense, it calculates the minimum length of the path to the bale with the turning radius, so if it has to drive a loop to get to a bale nearby, it may pick another one.

**Comment by pvaiko** [comment] 2024-03-12 20:44
> Field 31 was selected always on every try. But when I went back into the menu, the field changes back to 30 which is where it was working ok and finished the job. I’ve also tried setting a new field position and sending the collector their via AD with CP activated. It gets to the field and just sits at the field entrance not doing anything, if I manually press play it then starts bringing up the not near field. I then make sure it’s set which it won’t or is set but still won’t activate. Thinking about it the only update of mods I’ve had lately was the latest AD last week. Wonder if that’s interfering, I can’t recall what they updated. However it still does it if I manually drive to a new field and try

I see @schwiti6190 made a change a year ago in 122d05fb where the bale finder job gets the field position from the previous job if exists, that explains it. I have no idea why he made this change, @schwiti6190 ?

**Comment by coatsy35** [comment] 2024-03-12 22:00
> > > Field 31 was selected always on every try. But when I went back into the menu, the field changes back to 30 which is where it was working ok and finished the job. I’ve also tried setting a new field position and sending the collector their via AD with CP activated. It gets to the field and just sits at the field entrance not doing anything, if I manually press play it then starts bringing up the not near field. I then make sure it’s set which it won’t or is set but still won’t activate. Thinking about it the only update of mods I’ve had lately was the latest AD last week. Wonder if that’s interfering, I can’t recall what they updated. However it still does it if I manually drive to a new field and try
> > 
> > 
> > I see @schwiti6190 made a change a year ago in [122d05f](https://github.com/Courseplay/Courseplay_FS22/commit/122d05fbea1abf414eb72d9d82b031c04cc76461) where the bale finder job gets the field position from the previous job if exists, that explains it. I have no idea why he made this change, @schwiti6190 ?
> 
> Perhaps i'm picking a field position when i shouldn't? Does it in fact never need a field position now? Then because I set a field position I get a loop I can't get out of?
> 
> Should I just set AD to go to the field with CP enabled and then it should just work? I'll try that next time i change field. If that's the case, then perhaps a little fix that if someone selects the field it uses that and doesn't get in a loop. Would explain why a new vehicle works or a restart of the game I suppose.

Appears that's what happens. You can just tell it to go to a new field and it sets the field position to the new field automatically, however it still doesn't start - even if i try resetting the field. See below video of this happening, and if you watch it until the end you'll see what i mean. log file also attached. When i do get one working, there is no field highlight on the map.

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14578964/log.txt)

https://youtu.be/xz_xh9IlPq0

**Comment by coatsy35** [comment] 2024-03-12 22:26
The plot thickens. I took my tractor off the collector and put a tractor on that has never collected bales before a T7.315 this allowed me to start collecting. So i immediately stopped, put the previous tractor back on and it wouldn't let me collect. So I took that tractor off again and put the T7.315 back on which worked moments before and now that won't let me collect! says not near field again.

**Comment by Tensuko** [comment] 2024-03-14 17:22
The bug is something complete different.
The Target icon on the HUD opens the wrong AI Job in the AI Menu.
If you switch over to the correct one (bale collecting) you will find your target icons on the old field and you have to set them to the new one (just like you are used to and wich is intended) the Error here is "just visualy missleading" as it shows the field marked, but with the marker for the Generator on the Fieldwork Job.

**Comment by coatsy35** [comment] 2024-03-15 21:07
@pvaiko  @schwiti6190 Still experiencing issues with no path found when collecting even with the latest fixes dropped in my copy
Not as bad but it still happens often. The AI menu fix appears to have sorted the other bit though.
 
![fsScreen_2024_03_15_21_05_35](https://github.com/Courseplay/Courseplay_FS22/assets/122838698/da784de7-ca6c-4930-9d2d-d20bd60dc0ed)

[log.txt](https://github.com/Courseplay/Courseplay_FS22/files/14620738/log.txt)

**Comment by pvaiko** [comment] 2024-03-15 23:46
Try now, I missed something in the previous push.

**Comment by coatsy35** [comment] 2024-03-16 14:34
> Try now, I missed something in the previous push.

All appears to be working well now. Thank you.

**Comment by Tensuko** [comment] 2024-03-18 15:17
Wenn du dich mit git nicht aus kennst, warte auf das Release.

**Comment by franky-bb** [comment] 2024-03-21 11:05
Wann ist denn mit einem Update von CP zu rechnen, wo das Ballen laden gefixt ist.

**Comment by Tensuko** [comment] 2024-03-21 16:09
Wenn wir damit fertig sind.

**Closed** 2024-03-22 12:14 UTC
Labels: bug
