### ISSUE TITLE
[BUG_SP]Tractor pulling grain cart in indefinite loop trying to find Combine

### ISSUE THREAD

**Issue by Flashsolutions** [Courseplay/Courseplay_FS22#3431] opened 2024-09-15 17:27 UTC
**Steps to reproduce**
Field 8 on Deadwood map is planted with Corn and Case Combine is doing the harvesting.  When 50% full (per settings) a Case Steiger 620 tractor pulling a Demco 2200 grain cart attempts to circle around behind the stopped Combine and opens the cover but stops short of the pipe on the combine.  After waiting a bit, it repeats the performance, again never quite reaching the pipe.  This continues indefinitely.

This is a problem I have seen in earlier versions of Courseplay when I played years ago.  I thought it would have been fixed by now.

**Courseplay version**
Version used:  7.4.2.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
I don't have a log at the moment, but will try to get one if necessary.

**Map**
Deadwood

**Vehicles/ implements involved**
Which vehicle or implement? See above description
Mod yes/no ? No?

**Relevant script mods**
Mods like Autodrive or VCA and so on. Autodrive present but not applicable in this case.

**Comment by Tensuko** [comment] 2024-09-15 17:46
Screenshots will help to see whats going on.

**Comment by Tensuko** [comment] 2024-09-15 17:58
No problem at all.
When you use a mod combine, it could be a mod issue.
![grafik](https://github.com/user-attachments/assets/5f319c6e-ff5f-4216-9438-8688ffc127da)

Also when your header is too wide for a too small pipe, the header is physically in the way.....

**Comment by Tensuko** [comment] 2024-09-21 11:37
Closing as I can't reproduce this issue.
Need more details, then can reopen.
Best is a video with debug.

**Closed by Tensuko** 2024-09-21 11:37 UTC
Labels: bug, waiting for user
