### ISSUE TITLE
Bolko Z-643 trailed potato harvester causes turn script to fail.

### ISSUE THREAD

**Issue by Ghostfire110** [Courseplay/Courseplay_FS22#2415] opened 2023-03-27 23:43 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
using Lizard Bolko Z-643 turn on combine self-unload. filled to capacity and activates the auto-unload. after unloading, the tractor pulls away but cannot turn.

**Actual behavior**
the tractor doesn't turn causing it to lose the course

**Expected behavior**
the expected behavior is for the harvester/tractor to turn and to go back to harvesting

**Courseplay version**
Version used: 7.2.0.0

**Log**
https://gist.github.com/Ghostfire110/e690fa070a1b8575158d1975c78aaa38

**Map**
No Mans Land

**Vehicles/ implements involved**
Lizard Bolko Z-643- yes 
8150- no
halfpipe hp 20 -no

**Relevant script mods**
autodrive is an active mod, but not being used in this instance

**Comment by Tensuko** [comment] 2023-03-29 16:57
I was not able to reproduce this Issue.
But it might be fixed in 7.2.0.5 or on a higher state (so next Update).
You may try the latest Release: https://github.com/Courseplay/Courseplay_FS22/releases

**Comment by Ghostfire110** [comment] 2023-03-29 22:57
Tried on the new version, and now I can't even get it to unload, and of course, I didn't save the log file before I tried the new version. even with the same vehicle settings. it won't get close enough to the trailer to unload. would having my savegame help? and if so, how do I do that?

Heres the log with the new version:
https://gist.github.com/Ghostfire110/86dc7ce77884dd8c9fdcef0eef78d217

**Comment by Ghostfire110** [comment] 2023-03-29 23:01
I'm dumb, I still had the file open in notepad.

https://gist.github.com/Ghostfire110/d214077b4c56f2a9e4f8d64bd4714a8b

**Comment by schwiti6190** [comment] 2023-03-30 12:58
@Ghostfire110
Does the Bolko Z-643 unload when courseplay is active, when you drive next to it like with a combine?
Can you post an image of the situation, where it's not unloading ?

**Comment by Ghostfire110** [comment] 2023-03-30 21:47
![20230330164505_1](https://user-images.githubusercontent.com/62363959/228971730-781db4bb-3316-4cda-baf5-c67b075b287e.jpg)
here is an image, the tractor drives up as it should, but then it just sits there. the output point not being close enough to the truck to offload

**Comment by Tensuko** [comment] 2023-03-31 08:19
Thats a very strange "pipe"...
I am pretty sure we get the offset wrong, wich is a Mod Problem in this case.
That means we have to get closer.

What if you try to unload into an other trailer from basegame?
That would be the 2nd option that the truck loading platform is faulty.

**Comment by Tensuko** [comment] 2023-10-23 11:36
Looks like this problem affects only this mod. Unfortunately we only have limited time to spend on fixing bugs therefore we prefer working on issues that have an impact on standard vehicles or very popular mods. Sry.

**Closed by Tensuko** 2023-10-23 11:36 UTC
Labels: bug, waiting for user, can't reproduce
