### ISSUE TITLE
[BUG_SP] Power poles not detected

### ISSUE THREAD

**Issue by dangoodhead** [Courseplay/Courseplay_FS22#2909] opened 2023-10-27 21:04 UTC
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Steps to reproduce the behavior.
Generate a course on field 6 of court farm not detecting power poles when doing combining.

**Actual behavior**
A clear and concise description of what happen.
If you try to generate a course on field 6 of court farm with a combine, it doesn't detect the power poles in the field as a bypass.  If you use grass equipment like a mower, tedder, or windrower it works fine.

**Expected behavior**
The course should add the bypasses in like it does when doing grass work but fails to add them..

**Screenshots**

https://1drv.ms/i/s!Ag_p5NpWOkt9gqltici_x25J3LjRhQ?e=6chFfK

**Courseplay version**
Version used: 7.3.0.0

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.

**Map**
Map played on.  Court farm 1.1

**Vehicles/ implements involved**  new holland built into the map and also class lexion model 2023 
Which vehicle or implement?
Mod yes/no ?  both

**Relevant script mods**
Mods like Autodrive or VCA and so on.

**Comment by regs1980** [comment] 2023-10-28 07:56
It must be a mod problem, which does not come from CP.
I tested all these mods with the 7.3.0.0 version.
![2023-10-28 09_43_43-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/83a305eb-2a7d-49ec-b1dd-732af4e2e985)
![2023-10-28 09_51_52-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/972c0458-a3e5-4efb-9d9f-ffd7846cd3c9)
All of them detected the islands correctly.
Also in different working widths. 
![2023-10-28 09_53_11-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/534f02fc-7bdb-4028-a3f2-5313bc3b8e11)
![2023-10-28 09_53_23-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/bc752e48-91c4-4694-a305-6221c1b3ff2f)
![2023-10-28 09_53_48-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/88de1293-8dea-4ca6-b90a-8b427f911e98)
![2023-10-28 09_54_00-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/92cb382d-5a9f-46d1-b552-e41aae9cdcc6)
![2023-10-28 09_54_25-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/55a19c6a-5083-4241-986a-1d7612a4e852)
![2023-10-28 09_54_33-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/14937b46-df36-4a1a-b9d6-671ba19358f6)

**Comment by pvaiko** [comment] 2023-10-28 11:07
@regs1980 thank you for testing this, really appreciate it.

**Comment by pvaiko** [comment] 2023-10-28 11:08
@dangoodhead log with all debugs on?

**Comment by WeAreV3N0M** [comment] 2023-10-28 11:11
@pvaiko sorry for the off topic comment:
I have opened a new issue not long ago about island bypassing and it seems to have disappeared somehow. Can you pls help?

**Comment by Tensuko** [comment] 2023-10-28 11:25
It did not disappear, I moved it to the course generator repository.

**Comment by dangoodhead** [comment] 2023-11-04 22:11
Hi guys,  Thank you @pvaiko for taking the time to test this.  If its a mod issue causing it, is there a type of mod that could be a good place to start to isolate?

I think i know how to turn on debug.  I haven't done it before but if i turn that on and then try to create a course and it doesn't detect.  Do i then get the logs file from somewhere and then attach it here?

**Comment by dangoodhead** [comment] 2023-11-04 23:54
Hi all,  I have done some testing myself tonight.   I have a brand new save game.

The only mods on are the course play version linked above.   Easy devs tools and the class 2023 combine but haven't bought from the store this yet.  So just the machinery that comes with new farmer.

if i go to field 6 with new holland combine that comes with the map when there is grass in the field and generate it adds the cut outs.  If i then change the field fruit to wheat and ready to harvest and then try to make a course it does not cut them out.

@pvaiko Are you able to test this also please as the screen shots you added show that your field 6 still has grass in it.   Try it with wheat and ready to harvest and we'll see if this happens to you too.

**Comment by pvaiko** [comment] 2023-11-05 11:28
I have not tested it, @regs1980 did, thanks again.

If you are using Easy Dev Tools, maybe that is not smart enough to see the islands and covers the entire field with wheat. When you walk to the poles do you still see the islands, do they have the same shape as before or there is wheat under the poles?

**Comment by regs1980** [comment] 2023-11-05 12:06
@dangoodhead The problem is the map itself

Before working with the Dev Tool

![2023-11-05 12_55_09-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/d22b7964-dad6-40ca-b3ed-25b9e06ece9c)
![2023-11-05 12_55_23-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/945e16ce-b2db-4bb4-9a39-c752319f8dd7)

After working with the Dev Tool

![2023-11-05 12_56_14-Farming Simulator 22](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/524ff8e3-f446-4bce-81c9-ca64d4ecb80b)
![2023-11-05 12_56_35-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/3512dba4-185c-4514-87b0-712deb4d6fbf)

The problem is the islands that can also be bought.
These would have to be declared by the mapper as non-purchasable land, then the error would not occur.

![2023-11-05 12_55_23-2-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/8e48046d-8d78-4dd2-8549-988f5c9b7c79)
![2023-11-05 12_55_33-Greenshot](https://github.com/Courseplay/Courseplay_FS22/assets/13314443/4ba2ff8d-fa86-436e-acab-a6637ac87538)

**Comment by pvaiko** [comment] 2023-11-05 12:39
Closing as this is a map/easy dev tools issue, not Courseplay.

**Closed by pvaiko** 2023-11-05 12:39 UTC
Labels: bug, waiting for user
