### ISSUE TITLE
Disable fertilizing in sowing not working  + headland overlap

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#110] opened 2021-12-26 09:01 UTC
Version 7.0.0.3 and 7.0.0.4
when i disable the option to use fertilize in sowing machine, the worker still use fertilizer while sowing
got this with the Pottinger terrasem C6F
haven't tried with other for now.
playing on elmcreek

+ could you make again to option for the headland overpass
fe : for now i'm using lots of 6m width tools, but headland sometime are missed (some field not worked a the edge)
for now i juste set to the course with a 5,7m width and it's ok, mais the % for headland overpass from previous version was better :)

otherwise, thanks for the amazing work ;)

**Comment by pvaiko** [comment] 2021-12-26 11:17
Duplicate of #63

**Comment by pull2play** [comment] 2022-01-07 00:44
Apologies for bumping this, but would it be possible to increase headland overlap from 25% to as much as 50%? I've noticed that some wider implements (18m Kinze planter, some other mod seeders) still miss some areas even with 25%.

**Comment by Tensuko** [comment] 2022-01-07 17:52
> bumping

'bumping' comes from 'bump up my post' wich does not work on github, as last comment won't bring up the post like on Forums :) 

And no, Overlap of about 50% won't happen. If you talk about smooth corners, thats normal. Why not use sharp corners if can be pushed backwards ?

**Comment by pull2play** [comment] 2022-01-07 17:57
> 
> And no, Overlap of about 50% won't happen. If you talk about smooth corners, thats normal. Why not use sharp corners if can be pushed backwards ?

This happens on fields that have both sharp and smooth corners. I do use sharp for all my courses, but many larger implements still leave some small areas untouched. I suppose I'll have to "cheat" the system and just use a narrower work width and 25% overlap to create courses, that usually takes care of most problems. At least until you implement multi tool support :) Thanks anyway :)

**Comment by Tensuko** [comment] 2022-01-13 18:02
One part is done, the other is duplicate...

**Closed by Tensuko** 2022-01-13 18:02 UTC
