### ISSUE TITLE
[BUG_SP] CP + AD - multiple tool start on the same lane when started with AD :/

### ISSUE THREAD

**Issue by Chico0008** [Courseplay/Courseplay_FS22#1357] opened 2022-04-10 12:23 UTC
**Steps to reproduce**
Set a multipletool course
set one driver to le left, the 2nd to the right
make them go to work with AD, to autostart the course

when the get to the field, both driver work on the same lane, desptite tolding them to work left or right, they are both en the left

if i stop, and manually start the course, it's ok, but with AD, not :/

**Expected behavior**
Both driver goes to thei assigned working lane

**Courseplay version**
Version used: 7.0.1.9
AD : 2.0.0.5

Happens with all vehicle/implement
DK if it's a CP or AD (or both) bug

**Comment by schwiti6190** [comment] 2022-04-10 13:41
Duplicate of #1329

**Closed by schwiti6190** 2022-04-10 13:41 UTC
Labels: bug
