### ISSUE TITLE
A tractor should not need to be in a field to generate a course. [BUG_SP]

### ISSUE THREAD

**Issue by venquessa** [Courseplay/Courseplay_FS22#1780] opened 2022-07-19 15:37 UTC
**Steps to reproduce**
Steps to reproduce the behavior.

Try to generate a field without being in the field.  

**Actual behavior**
No "CP:Fieldwork" option is available.

**Expected behavior**
Courses should be generatable from anywhere on the map and from any vehicle.

**Courseplay version**
Version used:  7.1.0.1

This completely breaks the integration with AD, or the point of it anyway.  On a large map it can take 10 minutes to drive to the field.  I'd prefer to just generate the course, tell AD to drive to the field and enable CP integration. 

You are saying that every single time I want to run CP on a field I have to drive the implement to the field first?  

I also assume if I want to start at a particular point in the field I have to drive there too to define the start point?

No way, I'm downgrading for now thanks.

**Comment by Tritura2** [comment] 2022-07-19 15:49
Okay, can you tell us why you think you have to drive to the field to create a course?
Use the option „field position“ before creating a course to determine your start/end point.

![39590CC5-5813-4508-A79D-764B84666CB8](https://user-images.githubusercontent.com/37582657/179792855-02be4524-1bbc-4c42-9089-fde5d25263e0.jpeg)

By the way, this point needs a translation @Tensuko  😅

**Comment by shadow250** [comment] 2022-07-19 15:55
you can save and load courses so generating every time is not required.

**Comment by Tensuko** [comment] 2022-07-19 16:00
> By the way, this point needs a translation @Tensuko 😅

Should be in the actual Release.

@venquessa

First this is not a bug and what you discripe is wrong.
The ingame help menu shows you how you can generate a course.
You don't even have to sit inside a vehicle.
You can jump into a vehicle, click on no course and yea the right page pops up without a generator open, place the field position on the field you want and done!

Closing...

**Closed by Tensuko** 2022-07-19 16:00 UTC
Labels: bug

**Comment by Tensuko** [comment] 2022-07-19 16:02
And to add something more:
You clearly don't know how to use CP.

Before say something like this:

> You are saying that every single time I want to run CP on a field I have to drive the implement to the field first?
> 
> I also assume if I want to start at a particular point in the field I have to drive there too to define the start point?

Learn how to use it and read the ingame help menu!

**Comment by venquessa** [comment] 2022-07-19 16:17
It's the implement.  If CP doesn't like the implement, no course can be generated.  It's like course play doesn't exist.  The reason this confused me was I tried my spreader and nothing.  I tried my Semi truck, nothing.  I tried a brand new tractor at the shop and nothing.  

I could still change the stone pickers courses in the fields.  So I assumed it was that I needed to be in the field, which the documentation also suggested somewhere.   The reason the sprayer wasn't working was because the spreader bar was not attached, so CP seen it as a tanker that can't do field work.

I HATE computers trying to be smarter than humans and screwing it up.  And I'm a software engineer.  If I want to generate a course and drive a god **** conveyor belt around a field, course play should generate that course.  It's not courseplay's job to choose HOW I use it, you are Apple for god sake.  What purpose is there in putting in a limit like that?  None.

You can click on the "no course" button all you want, but it will not show the generator.  You can even have a tractor WITH a course and disconnect the implement and you "still" have course, but you can't edit it or generate a new one until you attach an implement that courseplay recognises.

If you attempt to record a course any other way it deletes it instantly.

And if anything, open a bug to have that documentation re-rewitten.  The FIRST statement on the course generator page should be how to open it.  In fact the course generator page doesn't even tell you how to open it.

I don't see any benefit from this "improvement" I think it will just cause more confusion than already exists with Course plays embracement of the fs22 GUI integration.

**Comment by Tritura2** [comment] 2022-07-19 16:23
> Should be in the actual Release.

I am using 7.1.0.1 and it is not. Or do you mean upcoming 7.1.0.2 by "actual Release"?

**Comment by venquessa** [comment] 2022-07-19 16:23
It was the implement.  The implement has to be attached and ready to use, recognised by CP.

The frustrating bit is, there is no indication of this, and the line of documentation suggesting it "and possible valid implement" isn't even on the course editor page.

Everything is telling you to select CP:Fieldwork, but it does not exist if you don't have a recognised implement attached,

What actually caught me out was I tested:
A spreader
A semi
A brand new tractor on it's own
Stone picker in a field

Only the stone picker would let me change it.

Turns out the spreader's distributor bar was not attached.  So no work width.  No CP.  No error.  No warnings.  Guess why.

**Comment by venquessa** [comment] 2022-07-19 16:36
> And to add something more: You clearly don't know how to use CP.
> 
> Before say something like this:
> 
> > You are saying that every single time I want to run CP on a field I have to drive the implement to the field first?
> > I also assume if I want to start at a particular point in the field I have to drive there too to define the start point?
> 
> Learn how to use it and read the ingame help menu!

I have been using course play for 7 years.  Since FS15.  The in game help text needs reworked.  It's difficult to follow.

My points where a little bit blunt/pointy/salty but they were questions.  You could have just said "no"  you don't.

In honesty I think my mistake was quite bizarre.  I figure you can't generate a course without a valid work width, so this must have been the case before too?  Did it not just allow you to open the course editor and say "unknown" for work width and allow you to set it manually?

Anyway, I have it working as you intended now.

**Comment by Tensuko** [comment] 2022-07-19 16:53
> I am using 7.1.0.1 and it is not. Or do you mean upcoming 7.1.0.2 by "actual Release"?

Will have to look it up, I thought schwiti did fix it but I will check :)

Just checked -> its fixed, maybe came with one of the last commits so 7.1.0.2 will have it in.


@venquessa

you are the first one haveing so many problems.
We told that a lot of things have changed, many things are new to everyone.
And yes you need a valid tool, it is written in the ingame help like that:
"To start off with your first CP job, you would have to select a vehicle and a possible valid implement which is supported for the job."

**Comment by Tensuko** [comment] 2022-07-20 05:42
No, won't happen.
