### ISSUE TITLE
Please Make a Popup Hud 

### ISSUE THREAD

**Issue by Lucky412** [Courseplay/Courseplay_FS22#105] opened 2021-12-26 05:32 UTC
Thank you for all of your work on CP, this game would be unplayable for long periods of time without it.  I have been playing and modding this game for over 10 years now. Would you consider bring the popup hud back as in the previous games. It is very frustrating going into the menu for courseplay

**Comment by knoxville73** [comment] 2021-12-26 07:33
Yes, I have the same feeling.  Without a Hud, CP isn't user friendly

**Comment by Mhuz** [comment] 2021-12-26 07:50
Can confirm, I prefer the old hud much more, right now it's much more inconvenient to reach and use. Same thing for the course generator hud

**Comment by iljarogoff** [comment] 2021-12-26 07:56
subscribe! a HUD makes using CP so much easier, the new setup inside AIhelper is very unintuitive

**Comment by Keppchen** [comment] 2021-12-26 09:59
#70 Is already discussed here

**Comment by Tensuko** [comment] 2021-12-26 10:13
Old HUD wont come back.
We have a mini hud in preparation.
Some things might now work smooth right now, but it will later.

**Comment by pvaiko** [comment] 2021-12-26 10:58
Duplicate of #70

**Comment by Tensuko** [comment] 2021-12-27 17:02
Discussed in another Issue and you can read it up here too:
https://github.com/Courseplay/Courseplay_FS22/wiki/FAQ

**Closed by Tensuko** 2021-12-27 17:02 UTC
